#!/usr/bin/env python3
"""Bake ui/toolbox/*.xml and ui/devinfo/devinfo.json into ui/core/offline_assets.js.

Opened from file://, the IDE cannot fetch anything: XMLHttpRequest is blocked
for local files, so xhrGET() in ui/core/ui.js falls back to copies baked into
the page. This script produces those copies as one JavaScript object, keyed by
the exact path xhrGET() asks for -- "toolbox/esp32.xml", "devinfo/devinfo.json".

ui/index.html pulls the result in only when it is itself loaded from file://,
so the served IDE keeps reading the real files and a toolbox edit shows up on
reload with no rebuild.

The device libraries used to need baking too; ui/core/pylibs.js (see
gen_pylibs.py) already covers them, for every protocol rather than just file://.

Run it with `make offline` after changing a toolbox or devinfo.json. Keep the
generated file committed -- `git status` after this target is how you notice it
went stale.
"""

import json
import os
import sys
import xml.etree.ElementTree as ET

UI = 'ui'
TOOLBOX = os.path.join(UI, 'toolbox')
DEVINFO = os.path.join('devinfo', 'devinfo.json')
OUT = os.path.join(UI, 'core', 'offline_assets.js')

HEADER = """// Generated by bake_offline.py from ui/toolbox/*.xml and ui/devinfo/ -- DO NOT EDIT.
// Run `make offline` after changing either.
//
// Maps the path xhrGET() in core/ui.js asks for to the contents of that file,
// verbatim. Only loaded when the IDE runs from file://, where fetching them is
// not allowed; served pages read the real files instead.
var OfflineAssets = {
"""

FOOTER = """};
"""


def read(path):
    """Read `ui/<path>`, keeping it byte-for-byte what the server would send."""
    with open(os.path.join(UI, path), encoding='utf-8', newline='') as f:
        return f.read()


def main():
    if not os.path.isdir(TOOLBOX):
        sys.exit(f'{TOOLBOX}: no such directory (run me from the repository root)')

    assets = {}

    # Toolboxes are handed to the caller as a parsed document either way, so
    # anything that is not well-formed XML would fail in the browser with a
    # <parsererror> node and an empty toolbox. Fail here instead, where the
    # message says which file.
    for name in sorted(os.listdir(TOOLBOX)):
        if not name.endswith('.xml'):
            continue
        path = f'toolbox/{name}'
        source = read(path)
        try:
            ET.fromstring(source)
        except ET.ParseError as e:
            sys.exit(f'{path}: not well-formed XML ({e})')
        assets[path] = source

    source = read(DEVINFO)
    json.loads(source)          # same reasoning: JSON.parse() would throw offline
    assets[DEVINFO.replace(os.sep, '/')] = source

    with open(OUT, 'w', encoding='utf-8', newline='\n') as out:
        out.write(HEADER)
        for path, source in assets.items():
            # json.dumps, not a `template literal`: a JS string literal needs no
            # thought about backticks, ${...}, backslash escapes or a stray
            # </script>, and it is what gen_pylibs.py already emits.
            out.write('%s: %s,\n' % (json.dumps(path), json.dumps(source)))
        out.write(FOOTER)

    print(f'{OUT}: {len(assets)} assets, {os.path.getsize(OUT)} bytes')


if __name__ == '__main__':
    main()
