#!/usr/bin/env python3
"""Bake ui/pylibs/*.py into ui/core/pylibs.js.

ui/pylibs/ is the single source of truth for the MicroPython libraries BIPES
installs on a board. This script turns that directory into one JavaScript
object so the UI can write a library to the board without fetching anything:
that works offline, from file://, and over every channel.

Keys are the name an "Install <name> library" toolbox button asks for --
always lowercased, because that is what installPyLib() in ui/core/code.js
derives from the button label. The real file name is kept alongside the
source, so mini_micropyGPS.py and CCS811.py land on the board spelled the way
their blocks import them.

Run it with `make pylibs` after adding or editing anything in ui/pylibs/.
"""

import hashlib
import json
import os
import re
import sys

PYLIBS = os.path.join('ui', 'pylibs')
OUT = os.path.join('ui', 'core', 'pylibs.js')
PAGE = os.path.join('ui', 'index.html')

HEADER = """// Generated by gen_pylibs.py from ui/pylibs/*.py -- DO NOT EDIT.
// Run `make pylibs` after changing anything in ui/pylibs/.
//
// Maps the library name an "Install <name> library" toolbox button asks for
// (lowercased, as installPyLib() in core/code.js derives it) to the file to
// write on the board and its source. Baked in rather than downloaded so that
// installing a library needs no network and works from file://.
var PyLibs = {
"""

FOOTER = """};
"""


def main():
    if not os.path.isdir(PYLIBS):
        sys.exit(f'{PYLIBS}: no such directory (run me from the repository root)')

    libs = {}
    for name in sorted(os.listdir(PYLIBS), key=str.lower):
        if not name.endswith('.py'):
            continue
        key = name[:-3].lower()
        if key in libs:
            sys.exit(f'{name}: two libraries collide on the name "{key}"; '
                     'the button label cannot tell them apart')
        # Universal newlines on purpose: two of the sources are CRLF (and
        # gfx.py has bare CRs), and the board should get plain LF.
        with open(os.path.join(PYLIBS, name), encoding='utf-8', newline=None) as f:
            libs[key] = (name, f.read())

    with open(OUT, 'w', encoding='utf-8') as out:
        out.write(HEADER)
        for key, (name, source) in libs.items():
            out.write('%s: {file: %s, source: %s},\n'
                      % (json.dumps(key), json.dumps(name), json.dumps(source)))
        out.write(FOOTER)

    print(f'{OUT}: {len(libs)} libraries, {os.path.getsize(OUT)} bytes')
    if stamp_page():
        print(f'{PAGE}: stamped')


def stamp_page():
    """Put a content hash on pylibs.js's `<script src>` in index.html.

    The same thing `make blocks` does for its own two generated files, and for
    the same reason: every other script on that page carries a hand-bumped
    `?ver=`, this one carried nothing, so a browser that had loaded it once
    kept it across a rebuild and a deploy. A stale copy here is not a subtle
    failure -- the standalone game blocks read their Python straight out of
    PyLibs and throw by name when a library is missing from it, and every
    "Install <name> library" button writes whatever the old copy held.
    """
    if not os.path.exists(PAGE):
        return False
    with open(PAGE, encoding='utf-8') as f:
        original = f.read()
    with open(OUT, 'rb') as f:
        digest = hashlib.sha256(f.read()).hexdigest()[:12]
    source = re.sub(r'(<script src="core/pylibs\.js)(\?v=[0-9a-f]+)?(")',
                    lambda m: f'{m.group(1)}?v={digest}{m.group(3)}', original)
    if source == original:
        return False
    with open(PAGE, 'w', encoding='utf-8', newline='\n') as f:
        f.write(source)
    return True


if __name__ == '__main__':
    main()
