"""Turn a Definition into the three artefacts a block has to exist in.

The JavaScript below is written to read like the hand-written files next to
it -- `Blockly.Blocks[...] = {init: function() {...}}` and
`Blockly.Python[...] = function(block) {...}` against the Blockly 6 API -- so
that a generated block and a hand-written one are the same kind of thing, and
converting a category is a move rather than a rewrite.
"""

from __future__ import annotations

import json
import re

from .spec import (ALIGNS, BUILTIN_TYPES, SOCKET_KINDS, Block, Button, Definition,
                   Label, Param, Row, Text, Variant)

BLOCKS_HEADER = """// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written blocks live in
// block_definitions.js; a block belongs in exactly one of the two.
"""

GENERATORS_HEADER = """// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written generators live in
// generator_stubs.js; a generator belongs in exactly one of the two.

// `unquote: true` on a param: the value goes into the Python as code, so the
// quotes Blockly.Python.quote_ wrapped it in have to come back off -- and it
// uses double quotes when the text itself contains a single one, and escapes
// the quote when the text contains both. Anything that is not a quoted literal
// (a variable, an expression) is left exactly as it is.
Blockly.Python.blockdefUnquote_ = function(code) {
  var match = /^'([\\s\\S]*)'$/.exec(code) || /^"([\\s\\S]*)"$/.exec(code);
  return match ? match[1].replace(/\\\\(['"\\\\])/g, '$1') : code;
};

// `kind: colour` on a param: the field holds "#ff0000" and the board wants
// (255,0,0), which is what every colour block in the tree emits.
Blockly.Python.blockdefColourRGB_ = function(hex) {
  var match = /^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(String(hex));
  if (!match) return '(0,0,0)';
  return '(' + parseInt(match[1], 16) + ',' + parseInt(match[2], 16) + ',' +
         parseInt(match[3], 16) + ')';
};

// `integer: true` on a param: the board cannot take a float there, so warn on
// the block rather than letting the program fail on the device. Guarded because
// `Tool` belongs to the page, and code is also generated without one.
Blockly.Python.blockdefWarnIfFloat_ = function(block, values) {
  var bad = values.some(function(v) {
    var f = parseFloat(v);
    return !isNaN(f) && f % 1 != 0;
  });
  try {
    Tool.warningIfTrue(block, [[function() { return bad; },
                               'Cannot convert float to int directly.']],
                       'blockdef_float');
  } catch (e) {}
};

// A socket the block's code interpolates, with nothing in it. These are the
// sockets no shadow fits -- an object, an iterable, a buffer -- so the flyout
// entry ships them empty and the user has to fill them. Left empty, the object
// socket on `len` gives `len()`: it parses, so nothing upstream notices, and
// the board answers with a TypeError traceback at the line that used it.
//
// The wording stops at what is certain. A few of these calls are legal with
// the argument missing -- `print()` prints a blank line, `uos.listdir()` lists
// the working directory -- so the warning says where the gap is and leaves
// what it means to the person who left it.
Blockly.Python.blockdefWarnIfEmpty_ = function(block, sockets) {
  var empty = [];
  for (var i = 0; i < sockets.length; i++) {
    if (sockets[i][1] === '')
      empty.push(sockets[i][0]);
  }
  try {
    Tool.warningIfTrue(block, [[function() { return empty.length > 0; },
                               'Nothing plugged in: ' + empty.join(', ') +
                               '.\\nThe Python this block writes has a gap there.']],
                       'blockdef_empty');
  } catch (e) {}
};

// `variants:` on a block: which board is selected decides what it emits. The
// value is the one on the `<option>` in index.html -- "ESP32S2", not the
// toolbox name and not the label the dropdown shows. Guarded, because code is
// also generated in places where the page around it is not there.
Blockly.Python.blockdefBoard_ = function() {
  try { return UI['workspace'].selector.value; } catch (e) { return ''; }
};
"""


def emit_blocks_js(definitions: list[Definition]) -> str:
    return _file(BLOCKS_HEADER, definitions, _block_js)


def emit_generators_js(definitions: list[Definition]) -> str:
    return _file(GENERATORS_HEADER, definitions, _generator_js)


def _file(header: str, definitions: list[Definition], emit) -> str:
    out = [header]
    for definition in definitions:
        if not definition.blocks:
            continue        # places blocks another file declares; owns none
        banner = f'{definition.category} ({definition.path.name})'
        out.append(f'\n// ---- {banner} {"-" * max(3, 72 - len(banner))}\n')
        for block in definition.blocks:
            out.append(emit(definition, block))
    return ''.join(out)


# --- Blockly.Blocks ---------------------------------------------------------


def _block_js(definition: Definition, block: Block) -> str:
    lines = [f"\nBlockly.Blocks['{block.type}'] = {{", '  init: function() {']

    for row in block.rows:
        lines.extend(_row_js(row))
    riding: list[Param] = []
    for param in block.params:
        # `row: next` holds a field back so it lands on the row of whatever
        # comes next -- a socket (relay_switch's on/off dropdown, move_servo's
        # servo number) or another field (the PID id in front of its dropdown).
        if param.row == 'next':
            riding.append(param)
            continue
        lines.extend(_param_js(param, riding))
        riding = []
    for row in block.footer:
        lines.extend(_row_js(row))

    if block.kind == 'value':
        lines.append(f'    this.setOutput(true, {_js(block.output) if block.output else "null"});')
    else:
        lines.append('    this.setPreviousStatement(true, null);')
        # No next connector for a block whose Python never returns: Blockly
        # then refuses the connection, instead of letting a student stack
        # blocks under a game that will never reach them.
        if block.has_next:
            lines.append('    this.setNextStatement(true, null);')

    colour = block.colour if block.colour is not None else definition.colour
    if colour is not None:
        lines.append(f'    this.setColour({_colour(colour)});')
    if block.inline is not None:
        lines.append(f'    this.setInputsInline({"true" if block.inline else "false"});')
    if block.tooltip.given:
        lines.append(f'    this.setTooltip({_text_js(block.tooltip)});')
    if block.help_url:
        lines.append(f'    this.setHelpUrl({_js(block.help_url)});')

    lines.append('  }')
    lines.append('};\n')
    return '\n'.join(lines)


def _row_js(row: Row) -> list[str]:
    lines = ['    this.appendDummyInput()']
    if row.align:
        lines.append(f'        .setAlign({ALIGNS[row.align]})')
    if row.image:
        lines.append(f'        .appendField(new Blockly.FieldImage({_js(row.image.src)}, '
                     f'{row.image.width}, {row.image.height}, {_js(row.image.alt)}))')
    if not row.label.empty:
        lines.append('        ' + _append_field(row.label))
    return _terminate(lines)


def _param_js(param: Param, riding: list[Param]) -> list[str]:
    if param.kind in SOCKET_KINDS:
        append = ('appendStatementInput' if param.kind == 'statements'
                  else 'appendValueInput')
        lines = [f'    this.{append}({_js(param.name)})']
        lines.append(f'        .setCheck({_js(param.type) if param.type else "null"})')
        if param.align:
            lines.append(f'        .setAlign({ALIGNS[param.align]})')
        lines.extend(_riding_js(riding))
        # The socket's own label comes last, after everything riding on it.
        if not param.label.empty:
            lines.append('        ' + _append_field(param.label))
        return _terminate(lines)

    lines = ['    this.appendDummyInput()']
    if param.align:
        lines.append(f'        .setAlign({ALIGNS[param.align]})')
    lines.extend(_riding_js(riding + [param]))
    return _terminate(lines)


def _riding_js(params: list[Param]) -> list[str]:
    """Label, field, label, field... in the order the params are written."""
    lines = []
    for param in params:
        if not param.label.empty:
            lines.append('        ' + _append_field(param.label))
        lines.append(f'        .appendField({_field_js(param)}, {_js(param.name)})')
        if not param.suffix.empty:
            lines.append('        ' + _append_field(param.suffix))
    return lines


def _append_field(text: Text) -> str:
    """A label, optionally named so it survives a save and can be translated."""
    if text.field:
        return (f'.appendField(new Blockly.FieldLabelSerializable({_text_js(text)}), '
                f'{_js(text.field)})')
    return f'.appendField({_text_js(text)})'


def _field_js(param: Param) -> str:
    if param.kind == 'dropdown':
        options = ', '.join(f'[{_text_js(label)}, {_js(value)}]'
                            for label, value in param.options)
        return f'new Blockly.FieldDropdown([{options}])'
    if param.kind == 'number':
        args = [_number(param.default if param.default is not None else 0)]
        for extra in (param.min, param.max, param.precision):
            if extra is None:
                break
            args.append(_number(extra))
        return f'new Blockly.FieldNumber({", ".join(args)})'
    if param.kind == 'checkbox':
        return f'new Blockly.FieldCheckbox({_js("TRUE" if param.default else "FALSE")})'
    if param.kind == 'angle':
        return f'new Blockly.FieldAngle({_number(param.default if param.default is not None else 0)})'
    if param.kind == 'colour':
        return f'new Blockly.FieldColour({_js(str(param.default or "#ff0000"))})'
    if param.kind == 'variable':
        return f'new Blockly.FieldVariable({_js(str(param.default or param.name))})'
    return f'new Blockly.FieldTextInput({_js("" if param.default is None else str(param.default))})'


def _terminate(lines: list[str]) -> list[str]:
    lines[-1] += ';'
    return lines


# --- Blockly.Python ---------------------------------------------------------


def _generator_js(definition: Definition, block: Block) -> str:
    lines = [f"\nBlockly.Python['{block.type}'] = function(block) {{"]

    # An import naming one of this block's params is built from what is plugged
    # in, so it has to wait until the inputs have been read -- `st7789_init`
    # registers `st7789_bl = machine.Pin(<backlight>, machine.Pin.OUT)` that
    # way. The rest keep their place at the top, where they have always been.
    names = {p.name for p in block.params} | ({'bus'} if block.i2c_bus else set())
    # `import: []` on a block means none at all, not even the family's -- the
    # three `uos` block-device blocks call a method on whatever is plugged in
    # and never mention `uos`.
    imports = block.imports if block.no_imports else definition.imports + block.imports
    fixed = [i for i in imports if not _mentions(i, names)]
    built = [i for i in imports if _mentions(i, names)]

    # Every block in the family registers the imports, not just the constructor:
    # definitions_ is a dict, so repeating one costs nothing, and a method block
    # dragged out on its own still produces importable code.
    for spec in fixed:
        lines.append(f'  Blockly.Python.definitions_[{_js(spec.key)}] = {_js(spec.line)};')

    reads: dict[str, str] = {}
    for param in block.params:
        var = f'{param.name}_'
        reads[param.name] = var
        lines.append(f'  var {var} = {_read_js(param)};')
    after_reads = len(lines)

    if block.i2c_bus:
        # Shared with the hand-written I2C blocks: one bus object per pin pair
        # (see Blockly.Python.i2cBus_ in generator_stubs.js).
        keywords = {p.name: p.keyword for p in block.params}
        parts = []
        for key in ('id', 'scl', 'sda', 'freq'):
            if key not in block.i2c_bus:
                continue
            name = block.i2c_bus[key]
            if isinstance(name, (int, float)):
                value = _js(name)
            elif keywords.get(name):
                # i2cBus_ splices the id in verbatim, so `keyword: id` on the
                # param is what decides between I2C(0, ...) and I2C(id=0, ...).
                value = f'{_js(keywords[name] + "=")} + {reads[name]}'
            else:
                value = reads[name]
            parts.append(f'{key}: {value}')
        if block.i2c_bus.get('soft'):
            parts.append('soft: true')
        lines.append(f'  var bus_ = Blockly.Python.i2cBus_({{{", ".join(parts)}}});')
        reads['bus'] = 'bus_'

    instance = block.instance or definition.instance
    for spec in built:
        key = _template_js(spec.key, reads, instance)
        line = _template_js(spec.line, reads, instance)
        lines.append(f'  Blockly.Python.definitions_[{key}] = {line};')

    integers = [reads[p.name] for p in block.params if p.integer]
    if integers:
        lines.append(f'  Blockly.Python.blockdefWarnIfFloat_(block, [{", ".join(integers)}]);')

    # Where the warning about empty sockets goes, once there is emitted code to
    # look at -- which of the reads it mentions is what decides.
    warn_at = len(lines)

    if block.variants:
        lines.extend(_variants_js(block, reads, instance))
    else:
        lines.append(f'  var code = {_code_js(definition, block, reads)};')

    # A socket is worth warning about when it arrives empty *and* the block
    # puts it in the Python it emits. A socket whose flyout entry carries a
    # shadow or a plugged block never arrives empty -- dragging its contents
    # out puts the shadow back -- and one nothing interpolates changes nothing
    # by being empty: `mcp23017_input` has a `pullup` socket its driver has no
    # parameter for, kept only because removing an input breaks saved programs.
    unfilled = [p for p in block.params
                if p.kind == 'input' and _shadow_xml(p) is None
                and _mentions_read(lines[after_reads:], reads[p.name])]
    if unfilled:
        pairs = ', '.join(f'[{_js(p.name)}, {reads[p.name]}]' for p in unfilled)
        lines.insert(warn_at, f'  Blockly.Python.blockdefWarnIfEmpty_(block, [{pairs}]);')
    if block.kind == 'value':
        lines.append('  return [code, Blockly.Python.ORDER_NONE];')
    elif block.code == '':
        # An init block that only registers definitions -- `sht20_init` builds
        # the bus and two helpers and emits nothing of its own. Adding the
        # newline would leave a blank line where the block sits.
        lines.append('  return code;')
    else:
        lines.append('  return code + "\\n";')
    lines.append('};\n')
    return '\n'.join(lines)


def _mentions_read(lines: list[str], var: str) -> bool:
    """Does anything the block emits actually use this socket's value?

    `var` is one read variable (`pullup_`), and the test is a whole-word one:
    `pin_` must not match inside `pin_mode_`.
    """
    pattern = re.compile(r'(?<![A-Za-z0-9_])' + re.escape(var) + r'(?![A-Za-z0-9_])')
    return any(pattern.search(line) for line in lines)


def _variants_js(block: Block, reads: dict[str, str], instance: str | None) -> list[str]:
    """One `if` per board, and the fallback as the `else`.

    The board is read once. Each branch registers its own imports before its
    code, because the two ports import different things -- CircuitPython's
    `wifi` module against MicroPython's `network`.
    """
    lines = ['  var code;', '  var board_ = Blockly.Python.blockdefBoard_();']
    for index, variant in enumerate(block.variants):
        if variant.device is not None:
            head = 'if' if index == 0 else '} else if'
            lines.append(f'  {head} (board_ == {_js(variant.device)}) {{')
        else:
            lines.append('  } else {')
        for spec in variant.imports:
            key = _template_js(spec.key, reads, instance)
            line = _template_js(spec.line, reads, instance)
            lines.append(f'    Blockly.Python.definitions_[{key}] = {line};')
        lines.append(f'    code = {_template_js(variant.code, reads, instance)};')
    lines.append('  }')
    return lines


def _mentions(spec, names: set[str]) -> bool:
    """Does this import interpolate one of the block's own values?"""
    return any(f'{{{name}}}' in spec.line or f'{{{name}}}' in spec.key for name in names)


def _read_js(param: Param) -> str:
    if param.kind == 'statements':
        # PASS is one indented `pass`. Without it an empty socket emits nothing
        # at all where Python needs a body, which is how all three of the
        # hand-written try/except blocks produced an IndentationError.
        return (f'(Blockly.Python.statementToCode(block, {_js(param.name)}) || '
                f'Blockly.Python.PASS)')
    if param.kind == 'input':
        read = (f'Blockly.Python.valueToCode(block, {_js(param.name)}, '
                f'Blockly.Python.ORDER_ATOMIC)')
        if param.unquote:
            # The value goes into the Python as code, not as a string, so the
            # quotes a text block wraps it in have to come back off.
            read = f'Blockly.Python.blockdefUnquote_({read})'
        return read
    if param.kind == 'colour':
        return (f'Blockly.Python.blockdefColourRGB_('
                f'block.getFieldValue({_js(param.name)}))')
    if param.kind == 'variable':
        return (f'Blockly.Python.nameDB_.getName(block.getFieldValue({_js(param.name)}), '
                f'Blockly.VARIABLE_CATEGORY_NAME)')
    if param.kind == 'checkbox':
        return f"(block.getFieldValue({_js(param.name)}) == 'TRUE' ? 'True' : 'False')"
    if param.kind == 'text':
        return f'JSON.stringify(block.getFieldValue({_js(param.name)}))'
    if param.emit:
        # The value stored in the saved program is not the Python it stands for.
        table = ', '.join(f'{_js(k)}: {_js(v)}' for k, v in param.emit.items())
        return f'{{{table}}}[block.getFieldValue({_js(param.name)})]'
    return f'block.getFieldValue({_js(param.name)})'


def _code_js(definition: Definition, block: Block, reads: dict[str, str]) -> str:
    """The Python this block emits, as a JavaScript string expression."""
    instance = block.instance or definition.instance
    if block.code is not None:
        return _template_js(block.code, reads, instance)

    names = block.args if block.args is not None else [p.name for p in block.params]
    keywords = {p.name: p.keyword for p in block.params}

    if block.attr:
        return _js(f'{instance}.{block.attr}')

    if block.constructor:
        target = (f'{definition.module}.{definition.cls}'
                  if _needs_prefix(definition, block) else definition.cls)
        head = f'{instance} = {target}('
    elif instance:
        head = f'{instance}.{block.fn}('
    elif _needs_prefix(definition, block):
        head = f'{definition.module}.{block.fn}('
    else:
        head = f'{block.fn}('

    if not names:
        return _js(head + ')')

    parts = [_js(head)]
    for index, name in enumerate(names):
        separator = ', ' if index else ''
        keyword = keywords.get(name)
        prefix = separator + (f'{keyword}=' if keyword else '')
        if prefix:
            parts.append(_js(prefix))
        parts.append(reads[name])
    parts.append(_js(')'))
    return ' + '.join(parts)


def _template_js(template: str, reads: dict[str, str], instance: str) -> str:
    """`code:` -- {param} interpolates, everything else is literal (newlines too)."""
    parts: list[str] = []
    literal = ''
    i = 0
    while i < len(template):
        if template[i] == '{' and '}' in template[i:]:
            end = template.index('}', i)
            name = template[i + 1:end]
            if name in reads:
                if literal:
                    parts.append(_js(literal))
                    literal = ''
                parts.append(reads[name])
            elif name == 'instance':
                literal += instance
            else:
                literal += template[i:end + 1]
            i = end + 1
        else:
            literal += template[i]
            i += 1
    if literal:
        parts.append(_js(literal))
    return ' + '.join(parts) if parts else _js('')


def _needs_prefix(definition: Definition, block: Block) -> bool:
    """`import x` means the class is `x.C`; `from x import C` means it is `C`.

    A block's own imports count too, so it does not matter whether the module
    is imported for the whole family or just for this block.
    """
    return any(spec.line.startswith(f'import {definition.module}')
               for spec in definition.imports + block.imports)


# --- toolbox XML ------------------------------------------------------------


def emit_category_xml(definition: Definition, indent: str = '    ', board: str = '',
                      pins: set[str] | None = None) -> str:
    # Normally no colour attribute: the blocks carry the colour, and only one
    # leaf category in this tree colours its own label.
    #
    # A `fragment:` definition writes no <category> at all: its markers sit
    # inside one that already exists, which is how the four blocks BIPES adds
    # to Blockly's Math category get generated without owning the category.
    colour = (f' colour="{_xml(definition.category_colour)}"'
              if definition.category_colour else '')
    lines = ([] if definition.fragment
             else [f'<category name="{_xml(definition.category)}"{colour}>'])
    for label in definition.labels:
        lines.append(f'  <label text="{_xml(label)}"></label>')
    for name in definition.library:
        lines.append(f'  <button text="Install {_xml(name)} library" '
                     f'callbackKey="installPyLib"></button>')
    for name in definition.examples:
        lines.append(f'  <button text="Load example: {_xml(name)}" '
                     f'callbackKey="loadExample"></button>')
    for name in definition.docs:
        lines.append(f'  <button text="Documentation and how to connect: {_xml(name)}" '
                     f'callbackKey="loadDoc"></button>')

    for entry in definition.entries:
        # `boards:` is how a category that is not the same everywhere says so:
        # the entry is listed on those toolboxes and left out of the others.
        if getattr(entry, 'offered', True) is False:
            # Defined, listed nowhere: a superseded block that saved programs
            # may still contain, so it has to exist and must not be offered.
            continue
        if entry.boards and board not in entry.boards:
            continue
        lines.append('')
        if isinstance(entry, Label):
            lines.append(f'  <label text="{_xml(entry.text)}"></label>')
            continue
        if isinstance(entry, Button):
            lines.append(f'  <button text="{_xml(entry.text)}" '
                         f'callbackKey="{entry.key}"></button>')
            continue
        overrides = definition.defaults.get(board, {})
        shadows = [(p, _shadow_xml(p, overrides.get(p.name, _UNSET), pins))
                   for p in entry.params]
        shadows = [(p, s) for p, s in shadows if s]
        if not shadows and not entry.fields:
            lines.append(f'  <block type="{entry.type}"></block>')
            continue
        lines.append(f'  <block type="{entry.type}">')
        for param, shadow in shadows:
            tag = 'statement' if param.kind == 'statements' else 'value'
            lines.append(f'    <{tag} name="{param.name}">')
            lines.extend('      ' + s for s in shadow)
            lines.append(f'    </{tag}>')
        for name, value in entry.fields.items():
            lines.append(f'    <field name="{_xml(name)}">{_xml(value)}</field>')
        lines.append('  </block>')

    if not any(line.lstrip().startswith('<block ') for line in lines):
        # Nothing to drag: every block in this family is `boards:`-restricted
        # away from this one. A category that opens on an empty flyout is a
        # dead end, so the board simply does not get it -- which is why
        # `toolboxes:` says where a category may appear, not where it must.
        return ''

    if not definition.fragment:
        lines.append('</category>')
    else:
        # The two-space indent every entry carries belongs to the <category>
        # that is not being written here.
        lines = [line[2:] if line.startswith('  ') else line for line in lines]
        while lines and not lines[0]:
            lines.pop(0)
    return '\n'.join(indent + line if line else '' for line in lines)


_UNSET = object()


def _shadow_xml(param: Param, override=_UNSET,
                pins: set[str] | None = None) -> list[str] | None:
    """The block sitting in an empty socket, so the toolbox entry is usable.

    `pins` is what the board's `devinfo.json` offers, when the caller knows: a
    `pinout` field naming a pin that is not in the dropdown makes Blockly warn
    and then fall back to the first one, so a default the board does not have
    is written as no field at all -- the same fallback, without the warning.
    """
    if param.kind == 'statements':
        # A stack has no shadow -- Blockly has no such thing -- but a real
        # block can start it, which is how `google_spreadsheet` arrives with a
        # cell in it. `emit_category_xml` wraps this in <statement>, not <value>.
        return _plug_xml(param.plug) if param.plug else None
    if param.kind != 'input':
        return None         # a field has no socket
    if param.plug:
        return _plug_xml(param.plug)
    if not param.shadow:
        return None
    default = param.default if override is _UNSET else override
    if param.pin:
        # One field, named PIN -- the pinout block has no other. Several
        # hand-written toolboxes name it SDA/SCL/RST instead, which Blockly
        # silently ignores. With no default the field is left out rather than
        # written empty: an empty one makes Blockly warn ("Cannot set the
        # dropdown's value to an unavailable option") and then fall back to the
        # first pin, which is what leaving it out does quietly.
        if default is None or (pins is not None and str(default) not in pins):
            return ['<shadow type="pinout"></shadow>']
        return ['<shadow type="pinout">',
                f'  <field name="PIN">{_xml(str(default))}</field>', '</shadow>']
    if param.type == 'String':
        return ['<shadow type="text">',
                f'  <field name="TEXT">{_xml("" if default is None else str(default))}</field>',
                '</shadow>']
    if param.type == 'Boolean':
        return ['<shadow type="logic_boolean">',
                f'  <field name="BOOL">{"TRUE" if default else "FALSE"}</field>',
                '</shadow>']
    if param.type == 'Number' or (param.type is None and isinstance(default, (int, float))):
        return ['<shadow type="math_number">',
                f'  <field name="NUM">{0 if default is None else default}</field>',
                '</shadow>']
    if param.type is None and isinstance(default, str):
        return ['<shadow type="text">',
                f'  <field name="TEXT">{_xml(default)}</field>', '</shadow>']
    return None     # no type and no default: we have no idea what fits


def _plug_xml(plug: dict) -> list[str]:
    """A block in the socket, with shadows of its own.

    `shadow: true` makes it a shadow of that type instead -- a placeholder the
    user can drop a different colour block onto, which is how every NeoPixel
    colour socket arrives.
    """
    tag = 'shadow' if plug['shadow'] else 'block'
    lines = [f'<{tag} type="{_xml(plug["type"])}">']
    for name, value in plug['values'].items():
        inner = _shadow_xml(Param(name=name, default=value))
        if inner is None:
            continue
        lines.append(f'  <value name="{_xml(name)}">')
        lines.extend('    ' + line for line in inner)
        lines.append('  </value>')
    for name, value in plug['fields'].items():
        lines.append(f'  <field name="{_xml(name)}">{_xml(value)}</field>')
    lines.append(f'</{tag}>')
    return lines


# --- helpers ----------------------------------------------------------------


def _js(value) -> str:
    """A JavaScript string literal. json.dumps, so quotes and \\ need no thought."""
    return json.dumps('' if value is None else str(value))


def _text_js(text: Text) -> str:
    """Block text: a literal, or a lookup in the loaded translation table."""
    if text.msg:
        return f'MSG[{_js(text.msg)}]'
    return _js(text.text)


def _colour(colour) -> str:
    """A hue is a number; anything else is a CSS colour name Blockly resolves."""
    return str(colour) if isinstance(colour, int) else _js(colour)


def _number(value) -> str:
    return json.dumps(value) if isinstance(value, (int, float)) else json.dumps(str(value))


def _xml(text: str) -> str:
    return (str(text).replace('&', '&amp;').replace('<', '&lt;')
            .replace('>', '&gt;').replace('"', '&quot;'))
