// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written blocks live in
// block_definitions.js; a block belongs in exactly one of the two.

// ---- AHT10/20 Sensor (ahtx0.blockdef.yaml) -----------------------------------

Blockly.Blocks['aht_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/aht20.JPG", 55, 55, "*"))
        .appendField(MSG["aht_init"]);
    this.appendDummyInput()
        .appendField("Init AHTx0 Sensor");
    this.appendDummyInput()
        .appendField(MSG["type"])
        .appendField(new Blockly.FieldDropdown([["AHT10", "AHT10"], ["AHT20", "AHT20"]]), "AHT_TYPE");
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Init AHT10 or AHT20 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['aht_read_temp'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read Temperature (Degrees C)");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Read AHT10/20 Temperature");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['aht_read_humidity'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read Humidity");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Read AHT10/20 Humidity");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Anemômetro (anemometro.blockdef.yaml) -----------------------------------

Blockly.Blocks['anemo_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/aneno.gif", 55, 55, "*"))
        .appendField("Iniciar Anen\u00f4metro");
    this.appendValueInput("Fun\u00e7\u00e3o")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Fun\u00e7\u00e3o");
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(new Blockly.FieldLabelSerializable("pin"), "ANENO_PIN_MSG");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(255);
  }
};

Blockly.Blocks['anemo_stop'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldLabelSerializable("Parar Anen\u00f4metro"), "STOP_ANENO");
    this.appendValueInput("Fun\u00e7\u00e3o")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Fun\u00e7\u00e3o");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(255);
  }
};

// ---- BH1750 Sensor (bh1750.blockdef.yaml) ------------------------------------

Blockly.Blocks['bh1750_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/bh1750.jpg", 55, 55, "*"))
        .appendField(MSG["bh1750_init"]);
    this.appendDummyInput()
        .appendField("Init BH1750 Sensor");
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Init BH1750 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bh1750_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read Ambient Light Level");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Read BH1750 Ambient Light Level");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Bluetooth REPL (bluetooth_repl.blockdef.yaml) ---------------------------

Blockly.Blocks['bluetooth_repl_setup'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Setup Web Bluetooth REPL");
    this.appendValueInput("name")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bluetooth name:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Setup Web Bluetooth REPL");
    this.setHelpUrl("www.bipes.net.br");
  }
};

Blockly.Blocks['bluetooth_repl_start'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Start Web Bluetooth REPL");
    this.appendValueInput("name")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bluetooth name:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Start REPL over Web Bluetooth");
    this.setHelpUrl("www.bipes.net.br");
  }
};

// ---- %{BKY_CAT_PRESS} (bmp.blockdef.yaml) ------------------------------------

Blockly.Blocks['bmp180_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["bmp180_init"]);
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp180_temperature'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["temperature"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Temperature from the BMP180 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp180_pressure'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["pressure"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Pressure from the BMP180 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp180_altitude'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["altitude"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Altitude from the BMP180 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp280_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init BMP280");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp280_measure'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("BMP280 Measure");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp280_sleep'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("BMP280 Sleep");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp280_temperature'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["temperature"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Temperature from the BMP280 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp280_pressure'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["pressure"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Pressure from the BMP280 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- %{BKY_CAT_AIR} (ccs811.blockdef.yaml) -----------------------------------

Blockly.Blocks['ccs811_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init CCS811");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['ccs811_data_ready'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("CCS811 Data Ready");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Air Quality Sensor CCS811 Data Ready");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['ccs811_eCO2'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("CCS811 CO2");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Air Quality Sensor CCS811 CO2 reading");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['ccs811_tVOC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("CCS811 tVOC");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Air Quality Sensor CCS811 VOC reading");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Character display (char_lcd.blockdef.yaml) ------------------------------

Blockly.Blocks['char_lcd_init'] = {
  init: function() {
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_LEFT)
        .appendField("Init I2C Character LCD Display");
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("with the PCF8574 Display Controller");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/lcd20x4.jpg", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("rows")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Rows");
    this.appendValueInput("columns")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Columns");
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("LCD I2C Address")
        .appendField(new Blockly.FieldDropdown([["0x27", "0x27"], ["0x3F", "0x3F"], ["", ""], ["", ""], ["0x20", "0x20"], ["0x21", "0x21"], ["0x22", "0x22"], ["0x23", "0x23"], ["0x24", "0x24"], ["0x25", "0x25"], ["0x26", "0x26"], ["0x27", "0x27"], ["0x38", "0x38"], ["0x39", "0x39"], ["0x3A", "0x3A"], ["0x3B", "0x3B"], ["0x3C", "0x3C"], ["0x3D", "0x3D"], ["0x3E", "0x3E"], ["0x3F", "0x3F"]]), "LCD_hex_address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_clear'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Clear LCD");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_putstr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write text on LCD");
    this.appendValueInput("text")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Text");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_moveto'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Move LCD Cursor to");
    this.appendValueInput("x")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("X");
    this.appendValueInput("y")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Y");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_backlight'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("LCD Backlight");
    this.appendDummyInput()
        .appendField("On/Off:")
        .appendField(new Blockly.FieldDropdown([["ON", "ON"], ["OFF", "OFF"]]), "on_off");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Turn On/Off the backlight");
  }
};

Blockly.Blocks['char_lcd_display'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("LCD Power");
    this.appendDummyInput()
        .appendField("On/Off:")
        .appendField(new Blockly.FieldDropdown([["ON", "ON"], ["OFF", "OFF"]]), "on_off");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Turn ON/Off the display");
  }
};

// ---- DC Motor (dc_motor.blockdef.yaml) ---------------------------------------

Blockly.Blocks['dc_motor_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init DC Motor");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/dcmotor.png", 55, 55, "*"));
    this.appendValueInput("pwm")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("PWM");
    this.appendValueInput("dir1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Dir1");
    this.appendValueInput("dir2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Dir2");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['dc_motor_power'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set DC Motor Power");
    this.appendValueInput("power")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Power");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['dc_motor_direction'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set DC Motor Direction");
    this.appendValueInput("dir")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Direction");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['dc_motor_stop'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Stop DC Motor");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- OneWire (ds18x20.blockdef.yaml) -----------------------------------------

Blockly.Blocks['onewire_ds18x20_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init OneWire Bus");
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("GPIO");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['onewire_ds18x20_scan'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Scan DS1820 sensors");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['onewire_ds18x20_convert'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Trigger DS1820 reading");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['onewire_ds18x20_read_temp'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("DS1820 Temperature reading");
    this.appendValueInput("rom")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ID");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- DS3231 RTC (ds3231.blockdef.yaml) ---------------------------------------

Blockly.Blocks['init_ds3231'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init DS3231 RTC");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/ds3231.jpg", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['set_time_ds3231'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set the Date and Time (24 Hr Clock)");
    this.appendValueInput("year")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Year");
    this.appendValueInput("month")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Month (1 - 12)");
    this.appendValueInput("day")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Day");
    this.appendValueInput("hour")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Hour (0 - 23)");
    this.appendValueInput("min")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Minutes (0 - 59)");
    this.appendValueInput("sec")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Seconds (0 - 59)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Set Time and Date");
  }
};

Blockly.Blocks['read_time_ds3231'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get the Date and Time (24 Hr Clock)");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Get the date and time");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['read_temp_ds3231'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get the Temperature");
    this.appendDummyInput()
        .appendField("Degrees ")
        .appendField(new Blockly.FieldDropdown([["C", "False"], ["F", "True"]]), "degree_f");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Get the temperature");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Rotatory Encoder (encoder.blockdef.yaml) --------------------------------

Blockly.Blocks['encoder_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init Rotatory Encoder");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/encoder.png", 55, 55, "*"));
    this.appendValueInput("p0")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ch0");
    this.appendValueInput("p1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ch1");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['encoder_reset'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Reset Encoder");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['encoder_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read Encoder Value");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- Camera (ESP32CAM) (esp32cam.blockdef.yaml) ------------------------------

Blockly.Blocks['esp32_cam_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("ESP32-CAM Init");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Init ESP32-CAM camera");
    this.setHelpUrl("www.bipes.net.br");
  }
};

Blockly.Blocks['esp32_cam_capture'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("ESP32-CAM capture photo");
    this.setOutput(true, null);
    this.setColour(0);
    this.setTooltip("Take photo with ESP32-CAM camera");
    this.setHelpUrl("www.bipes.net.br");
  }
};

Blockly.Blocks['esp32_cam_red_led'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Control ESP32-CAM red LED");
    this.appendValueInput("value")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("to");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Control ESP32-CAM Red LED");
    this.setHelpUrl("bipes.net.br");
  }
};

Blockly.Blocks['esp32_cam_white_led'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Control ESP32-CAM flashlight");
    this.appendValueInput("value")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("to");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Control ESP32-CAM White LED (flashlight)");
    this.setHelpUrl("bipes.net.br");
  }
};

// ---- gc (gc.blockdef.yaml) ---------------------------------------------------

Blockly.Blocks['gc_enable'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(" enable");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: enable() Enable automatic garbage collection. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/gc.html");
  }
};

Blockly.Blocks['gc_disable'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(" disable");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: disable() Disable automatic garbage collection. Heap memory can still be allocated, and garbage collection can still be initiated manually using :meth:`gc.collec ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/gc.html");
  }
};

Blockly.Blocks['gc_collect'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(" collect");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: collect() Run a garbage collection. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/gc.html");
  }
};

Blockly.Blocks['gc_mem_alloc'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(" mem_alloc");
    this.setOutput(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: mem_alloc() Return the number of bytes of heap RAM that are allocated. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/gc.html");
  }
};

Blockly.Blocks['gc_mem_free'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(" mem_free");
    this.setOutput(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: mem_free() Return the number of bytes of available heap RAM, or -1 if this amount is not known. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/gc.html");
  }
};

Blockly.Blocks['gc_threshold'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" threshold");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(" ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/gc.html");
  }
};

// ---- GPS (gps.blockdef.yaml) -------------------------------------------------

Blockly.Blocks['gps_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GPS Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/ublox_gps.png", 55, 55, "*"));
    this.appendValueInput("uart")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("UART");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX");
    this.appendValueInput("rx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("RX");
    this.appendValueInput("bps")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Baud Rate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_update'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update GPS Readings");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_coord_format'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Coordinate Format ")
        .appendField(new Blockly.FieldDropdown([["Decimal Degrees (DD)", "dd"], ["Degree Minute Second (DMS)", "dms"]]), "format");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_lat'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Latitude");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_long'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Longitude");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_height'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Altitude");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_speed'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Speed");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_date'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Date");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_time'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Timestamp");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- GY33 I2C (gy33_i2c.blockdef.yaml) ---------------------------------------

Blockly.Blocks['gy33_i2c_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GY33 I2C Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/GY-33.jpg", 65, 65, "*"));
    this.appendValueInput("id")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ID");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("freq")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Frequency");
    this.appendValueInput("addr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Initalizes the GY-33 I2C Interface");
  }
};

Blockly.Blocks['gy33_i2c_led_pwr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set LED Power");
    this.appendValueInput("led_pwr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Power");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the brightness of the LED (0 - 10)");
  }
};

Blockly.Blocks['gy33_i2c_cal_white_balance'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Balance Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white balance calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_i2c_cal_white'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_i2c_cal_black'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Black Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a black calibration. The sensor should first be placed on a suitable black surface.");
  }
};

Blockly.Blocks['gy33_i2c_get_all'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get All Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing the Raw Red, Raw Green, Raw Blue, Clear, Lux, Color Temperature, Red, Green, Blue, Color values");
  }
};

Blockly.Blocks['gy33_i2c_get_raw'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Raw Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing only the Raw Red, Raw Green, Raw Blue, Clear values.");
  }
};

Blockly.Blocks['gy33_i2c_get_calibrated'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Calibrated Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing only the calibrated Red, Green, Blue, and Clear values.");
  }
};

// ---- GY33 UART (gy33_uart.blockdef.yaml) -------------------------------------

Blockly.Blocks['gy33_uart_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GY33 UART Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/GY-33.jpg", 65, 65, "*"));
    this.appendValueInput("uart")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("UART");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX");
    this.appendValueInput("rx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("RX");
    this.appendValueInput("bps")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Baud Rate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Initalizes the GY-33 UART");
  }
};

Blockly.Blocks['gy33_uart_led_pwr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set LED Power");
    this.appendValueInput("led_pwr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Power");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the brightness of the LED (0 - 10)");
  }
};

Blockly.Blocks['gy33_uart_integration_time'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Integration Time");
    this.appendDummyInput()
        .appendField("Time (ms)")
        .appendField(new Blockly.FieldDropdown([["700", "700"], ["154", "154"], ["100 (Default)", "100"], ["24", "24"], ["2.4", "2.4"]]), "TIME");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the integration time in milliseconds");
  }
};

Blockly.Blocks['gy33_uart_baud_rate'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Internal UART Baudrate");
    this.appendDummyInput()
        .appendField("Time (ms)")
        .appendField(new Blockly.FieldDropdown([["9600", "9600"], ["115200", "115200"]]), "BAUDRATE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the baudrate");
  }
};

Blockly.Blocks['gy33_uart_i2c_addr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set I2C Address");
    this.appendValueInput("addr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the desired i2c address. Must be between 0 to 127");
  }
};

Blockly.Blocks['gy33_uart_cal_white_balance'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Balance Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white balance calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_uart_cal_white'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_uart_cal_black'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Black Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a black calibration. The sensor should first be placed on a suitable black surface.");
  }
};

Blockly.Blocks['gy33_uart_get_raw'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Raw Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a list containing the raw Red, Green, Blue, Clear values.");
  }
};

Blockly.Blocks['gy33_uart_get_lcc'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get LCC Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a list containing the Lux (brightness), Color Temperature, Color values.");
  }
};

Blockly.Blocks['gy33_uart_get_processed'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Processed Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a list containing the processed Red, Green, Blue values.");
  }
};

// ---- %{BKY_CAT_ULTRASOUND} (hcsr04.blockdef.yaml) ----------------------------

Blockly.Blocks['hcsr_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/hcsr04.png", 55, 55, "*"))
        .appendField(MSG["hcsr_init"]);
    this.appendValueInput("echo")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("echo pin");
    this.appendValueInput("trigger")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("trigger pin");
    this.appendValueInput("timeout")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(new Blockly.FieldLabelSerializable(MSG["hcsr_timeout"]), "DHT_PIN_MSG");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip(MSG["hcsr_init"]);
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['hcsr_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldLabelSerializable(MSG["get_distance"]), "MSG_READ_DHT_TEMP");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip(MSG["measure_distance"]);
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Oximeter (max30100.blockdef.yaml) ---------------------------------------

Blockly.Blocks['max30100_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init MAX30100 Sensor");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/max30100.png", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['max30100_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update MAX30100 Reading");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['max30100_red'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get MAX30100 Red Value");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['max30100_ir'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get MAX30100 IR Value");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- LED Matrix (max7219.blockdef.yaml) --------------------------------------

Blockly.Blocks['max7219_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/matrix.png", 55, 55, "*"))
        .appendField("Init MAX7219 LED Matrix");
    this.appendValueInput("spi")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SPI");
    this.appendValueInput("clk")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("CLK");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX");
    this.appendValueInput("cs")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("CS");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Init MAX7219 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_write'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write a Single Character to LED Matrix");
    this.appendValueInput("x")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("X");
    this.appendValueInput("y")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Y");
    this.appendValueInput("character")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("CHARACTER");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Write to MAX7219 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_line'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Draw a line on LED Matrix");
    this.appendValueInput("x1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Initial X position");
    this.appendValueInput("y1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Initial Y position");
    this.appendValueInput("x2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Final X position");
    this.appendValueInput("y2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Final Y position");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Draw a line on LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_rect'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Draw a rectangle outline on LED Matrix");
    this.appendValueInput("x1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Initial X position");
    this.appendValueInput("y1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Initial Y position");
    this.appendValueInput("x2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Width");
    this.appendValueInput("y2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Height");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Draw a rectangle on LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_fill_rect'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Draw a solid rectangle on LED Matrix");
    this.appendValueInput("x1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Initial X position");
    this.appendValueInput("y1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Initial Y position");
    this.appendValueInput("x2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Width");
    this.appendValueInput("y2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Height");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Draw a solid rectangle on LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_scroll'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("scroll the LED Matrix");
    this.appendValueInput("x")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Scroll back(-) or forth(+)");
    this.appendValueInput("y")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Scroll up (-) or down(+)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Scroll the LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_clear'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Clear LED Matrix");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Clear LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_fill'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Fill LED Matrix");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Fill LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['max7219_brig'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Brightness of Led Matrix");
    this.appendValueInput("brig")
        .setCheck("Number")
        .appendField("value (0-15)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Set brightness of MAX7129 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- I/O Expander (mcp23017.blockdef.yaml) -----------------------------------

Blockly.Blocks['mcp23017_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init MCP23017");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['mcp23017_setup'] = {
  init: function() {
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("MCP23017 direction setup (IN/OUT)");
    this.appendValueInput("value")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(MSG["to"]);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("MCP23017 directin setup");
    this.setHelpUrl("bipes.net.br");
  }
};

Blockly.Blocks['mcp23017_output'] = {
  init: function() {
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("MCP23017 set pin");
    this.appendValueInput("value")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(MSG["to"]);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("MCP23017 Write to GPIO digital pin");
    this.setHelpUrl("bipes.net.br");
  }
};

Blockly.Blocks['mcp23017_input'] = {
  init: function() {
    this.appendValueInput("pin")
        .setCheck("Number")
        .appendField("MCP23017 input pin");
    this.appendValueInput("pullup")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Pull-up");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("MCP23017 Read digital pin");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- MPR121 (mpr121.blockdef.yaml) -------------------------------------------

Blockly.Blocks['mpr121_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init MPR121 Keypad");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/mpr121.jpg", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Initializes the MPR121 interface");
  }
};

Blockly.Blocks['mpr121_key_pressed'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Is Key Pressed");
    this.appendValueInput("id")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("KEY");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Is key pressed");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- PCA9685 Servo Driver (pca9685.blockdef.yaml) ----------------------------

Blockly.Blocks['init_pca9685'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init PCA9685 Servo Driver");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/pca9685.jpg", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("min_pulse_width")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Min Pulse Width");
    this.appendValueInput("max_pulse_width")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Max Pulse Width");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['move_pca9685'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Position Servo");
    this.appendValueInput("servo_id")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Servo ID (0 - 15)");
    this.appendValueInput("angle")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Angle (0 - 180");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Position one of the servos");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Pluviômetro (pluviometro.blockdef.yaml) ---------------------------------

Blockly.Blocks['pluvio_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/pluivio.gif", 70, 70, "*"))
        .appendField("Iniciar Plui\u00f4metro");
    this.appendValueInput("Fun\u00e7\u00e3o")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Fun\u00e7\u00e3o");
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(new Blockly.FieldLabelSerializable("pin"), "PLUVIO_PIN");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(100);
  }
};

Blockly.Blocks['pluvio_stop'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldLabelSerializable("Parar Plvi\u00f4metro"), "STOP_PLUVIO");
    this.appendValueInput("Fun\u00e7\u00e3o")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Fun\u00e7\u00e3o");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(100);
  }
};

// ---- TCP/IP Socket (socket.blockdef.yaml) ------------------------------------

Blockly.Blocks['net_socket_connect'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("TCP/IP Socket Connect");
    this.appendValueInput("host")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Host:");
    this.appendValueInput("port")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Port:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['net_socket_receive'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Socket Receive");
    this.appendValueInput("bytes")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bytes to receive:");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['net_socket_send'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Socket Send");
    this.appendValueInput("bytes")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Data:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['net_socket_close'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Socket Close");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- Stepper Motor (stepper.blockdef.yaml) -----------------------------------

Blockly.Blocks['stepper_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init Stepper Motor");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/stepper.png", 55, 55, "*"));
    this.appendValueInput("p0")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Pin0");
    this.appendValueInput("p1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Pin1");
    this.appendValueInput("p2")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Pin2");
    this.appendValueInput("p3")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Pin3");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['stepper_step'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Stepper Step");
    this.appendValueInput("steps")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Steps");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- sys (sys.blockdef.yaml) -------------------------------------------------

Blockly.Blocks['sys_exit'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" exit");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: exit(retval=0, /) Terminate current program with a given exit code. Underlyingly, this function raise as `SystemExit` exception. If an argument is given, its ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/sys.html");
  }
};

Blockly.Blocks['sys_atexit'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" atexit");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: atexit(func) Register functions.txt onlyfunctions.txt to be called upon termination. functions.txt onlyfunctions.txt must be a callable that takes no arguments, or ``None`` to disable the call. The ``atexit`` ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/sys.html");
  }
};

Blockly.Blocks['sys_print_exception'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" print_exception");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: print_exception(exc, file=sys.stdout, /) Print exception with a traceback to a file-like object Makefile (or `sys.stdout` by default). ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/sys.html");
  }
};

// ---- 4 Digit Display (tm1637.blockdef.yaml) ----------------------------------

Blockly.Blocks['tm1637_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/tm1637.jpg", 55, 55, "*"))
        .appendField("Init TM1637 4 Digit Display");
    this.appendValueInput("clk")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("CLK");
    this.appendValueInput("dio")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("DIO");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Init TM1637 4 Digit Display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_write_char'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write a Single Character to Display");
    this.appendValueInput("character")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Character");
    this.appendValueInput("position")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Position (0-3)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Write a character to the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_write_text'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write Text to Display");
    this.appendValueInput("text")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Text");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Write text to the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_scroll_text'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Scroll Text to Display");
    this.appendValueInput("text")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Text");
    this.appendValueInput("speed")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Speed (ms)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Scroll text to the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_set_time'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write Time to Display");
    this.appendValueInput("hour")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Hour");
    this.appendValueInput("minute")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Minute");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Write time to the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_set_temperature'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write Temperature to Display");
    this.appendValueInput("temperature")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Temperature");
    this.appendDummyInput()
        .appendField("Degrees")
        .appendField(new Blockly.FieldDropdown([["C", "True"], ["F", "False"]]), "DEGREE_TYPE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Write temperature to the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_set_brightness'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set the Brightness of the Display");
    this.appendValueInput("brightness")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("BRIGHTNESS (0-7)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Set the brightness of the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1637_clear'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Clear the Display");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Clear the display");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- LED Matrix (tm1640.blockdef.yaml) ---------------------------------------

Blockly.Blocks['tm1640_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/matrix.png", 55, 55, "*"))
        .appendField("Start TM1640 LED Matrix");
    this.appendValueInput("clk")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("CLK");
    this.appendValueInput("dio")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("DIO");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Start TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1640_write'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write array to Led Matrix");
    this.appendValueInput("vector")
        .setCheck("String")
        .appendField("LED array value");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Write to TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1640_brig'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Brightness of Led Matrix");
    this.appendValueInput("brig")
        .setCheck("Number")
        .appendField("value (1-7)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Set brightness of TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1640_num'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write Number on Led Matrix");
    this.appendValueInput("num")
        .setCheck("Number")
        .appendField("value (0-9)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Write number on TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- UART (uart.blockdef.yaml) -----------------------------------------------

Blockly.Blocks['uart_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init UART Serial Port");
    this.appendValueInput("port")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Port:");
    this.appendValueInput("baud")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Baud rate:");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX Pin:");
    this.appendValueInput("rx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("RX Pin:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_write'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Send data to UART");
    this.appendValueInput("buf")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Data:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read data from UART");
    this.appendValueInput("s")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bytes to read:");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_read_into'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read from UART into a Buffer");
    this.appendValueInput("b")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Destination Buffer:");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_readline'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read one line from UART");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_read_all'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read all data from UART");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_any'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Check to see if the uart has data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- ubinascii (ubinascii.blockdef.yaml) -------------------------------------

Blockly.Blocks['ubinascii_hexlify'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" hexlify");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(" ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ubinascii.html");
  }
};

Blockly.Blocks['ubinascii_unhexlify'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" unhexlify");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: unhexlify(data) Convert hexadecimal data to binary representation. Returns bytes string. (i.e. inverse of hexlify) ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ubinascii.html");
  }
};

Blockly.Blocks['ubinascii_a2b_base64'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" a2b_base64");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: a2b_base64(data) Decode base64-encoded data, ignoring invalid characters in the input. Conforms to `RFC 2045 s.6.8 <https://tools.ietf.org/html/rfc2045#section-6.8> ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ubinascii.html");
  }
};

Blockly.Blocks['ubinascii_b2a_base64'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" b2a_base64");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: b2a_base64(data) Encode binary data in base64 format, as in `RFC 3548 <https://tools.ietf.org/html/rfc3548.html>`_. Returns the encoded data ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ubinascii.html");
  }
};

// ---- ucryptolib (ucryptolib.blockdef.yaml) -----------------------------------

Blockly.Blocks['ucryptolib_encrypt'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" encrypt");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(" ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ucryptolib.html");
  }
};

Blockly.Blocks['ucryptolib_decrypt'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" decrypt");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(" ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ucryptolib.html");
  }
};

// ---- uheapq (uheapq.blockdef.yaml) -------------------------------------------

Blockly.Blocks['uheapq_heappush'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" heappush");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: heappush(heap, item) Push the ``item`` onto the ``heap``. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/uheapq.html");
  }
};

Blockly.Blocks['uheapq_heappop'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" heappop");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: heappop(heap) Pop the first item from the ``heap``, and return it. Raises IndexError if heap is empty. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/uheapq.html");
  }
};

Blockly.Blocks['uheapq_heapify'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" heapify");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: heapify(x) Convert the list ``x`` into a heap. This is an in-place operation. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/uheapq.html");
  }
};

// ---- ujson (ujson.blockdef.yaml) ---------------------------------------------

Blockly.Blocks['ujson_dump'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" dump");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: dump(obj, stream) Serialise *obj* to a JSON string, writing it to the given *stream*. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html");
  }
};

Blockly.Blocks['ujson_dumps'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" dumps");
    this.setOutput(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: dumps(obj) Return *obj* represented as a JSON string. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html");
  }
};

Blockly.Blocks['ujson_load'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" load");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: load(stream) Parse the given *stream*, interpreting it as a JSON string and deserialising the data to a Python object. The resulting object is ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html");
  }
};

Blockly.Blocks['ujson_loads'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" loads");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: loads(str) Parse the JSON *str* and return an object. Raises :exc:`ValueError` if the string is not correctly formed. ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html");
  }
};

// ---- EMAIL (umail.blockdef.yaml) ---------------------------------------------

Blockly.Blocks['umail_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init uMail Email Sender");
    this.appendValueInput("host")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Host:");
    this.appendValueInput("port")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Port:");
    this.appendValueInput("username")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Username:");
    this.appendValueInput("password")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Password:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['umail_send'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Send email");
    this.appendValueInput("to")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("To email:");
    this.appendValueInput("subject")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Subject:");
    this.appendValueInput("contents")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Email message:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- uzlib (uzlib.blockdef.yaml) ---------------------------------------------

Blockly.Blocks['uzlib_decompress'] = {
  init: function() {
    this.appendValueInput("pIn")
        .setCheck(null)
        .appendField(" decompress");
    this.setOutput(true, null);
    this.setColour(0);
    this.setTooltip(".. function:: decompress(data, wbits=0, bufsize=0, /) Return decompressed *data* as bytes. *wbits* is DEFLATE dictionary window size used during compression (8-15, the dictionary size is power of 2 of ");
    this.setHelpUrl("https://docs.micropython.org/en/latest/library/uzlib.html");
  }
};

// ---- Time of Flight (vl53l0x.blockdef.yaml) ----------------------------------

Blockly.Blocks['init_vl53l0x'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init VL53L0X");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/vl53l0x.jpg", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['vl53l0x_read_tof'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldLabelSerializable("Time of Flight"), "MSG_READ_TOF");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Time of Flight (mm)");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- WebREPL (webrepl.blockdef.yaml) -----------------------------------------

Blockly.Blocks['webrepl_setup'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("WebREPL Setup");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Configure WebREPL");
    this.setHelpUrl("www.bipes.net.br");
  }
};

Blockly.Blocks['webrepl_start'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Start WebREPL");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Start WebREPL Server");
    this.setHelpUrl("www.bipes.net.br");
  }
};
