// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written blocks live in
// block_definitions.js; a block belongs in exactly one of the two.

// ---- Bluetooth REPL (bluetooth_repl.blockdef.yaml) ---------------------------

Blockly.Blocks['bluetooth_repl_setup'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Setup Web Bluetooth REPL");
    this.appendValueInput("name")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bluetooth name:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Setup Web Bluetooth REPL");
    this.setHelpUrl("www.bipes.net.br");
  }
};

Blockly.Blocks['bluetooth_repl_start'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Start Web Bluetooth REPL");
    this.appendValueInput("name")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bluetooth name:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(0);
    this.setTooltip("Start REPL over Web Bluetooth");
    this.setHelpUrl("www.bipes.net.br");
  }
};

// ---- %{BKY_CAT_PRESS} (bmp.blockdef.yaml) ------------------------------------

Blockly.Blocks['bmp180_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["bmp180_init"]);
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp180_temperature'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["temperature"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Temperature from the BMP180 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp180_pressure'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["pressure"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Pressure from the BMP180 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp180_altitude'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["altitude"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Altitude from the BMP180 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp280_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init BMP280");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp280_measure'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("BMP280 Measure");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp280_sleep'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("BMP280 Sleep");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("");
  }
};

Blockly.Blocks['bmp280_temperature'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["temperature"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Temperature from the BMP280 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['bmp280_pressure'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(MSG["pressure"]);
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Pressure from the BMP280 sensor");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- %{BKY_CAT_AIR} (ccs811.blockdef.yaml) -----------------------------------

Blockly.Blocks['ccs811_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init CCS811");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['ccs811_data_ready'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("CCS811 Data Ready");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Air Quality Sensor CCS811 Data Ready");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['ccs811_eCO2'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("CCS811 CO2");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Air Quality Sensor CCS811 CO2 reading");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['ccs811_tVOC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("CCS811 tVOC");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("Air Quality Sensor CCS811 VOC reading");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Character display (char_lcd.blockdef.yaml) ------------------------------

Blockly.Blocks['char_lcd_init'] = {
  init: function() {
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_LEFT)
        .appendField("Init I2C Character LCD Display");
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("with the PCF8574 Display Controller");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/lcd20x4.jpg", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("rows")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Rows");
    this.appendValueInput("columns")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Columns");
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("LCD I2C Address")
        .appendField(new Blockly.FieldDropdown([["0x27", "0x27"], ["0x3F", "0x3F"], ["", ""], ["", ""], ["0x20", "0x20"], ["0x21", "0x21"], ["0x22", "0x22"], ["0x23", "0x23"], ["0x24", "0x24"], ["0x25", "0x25"], ["0x26", "0x26"], ["0x27", "0x27"], ["0x38", "0x38"], ["0x39", "0x39"], ["0x3A", "0x3A"], ["0x3B", "0x3B"], ["0x3C", "0x3C"], ["0x3D", "0x3D"], ["0x3E", "0x3E"], ["0x3F", "0x3F"]]), "LCD_hex_address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_clear'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Clear LCD");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_putstr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write text on LCD");
    this.appendValueInput("text")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Text");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_moveto'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Move LCD Cursor to");
    this.appendValueInput("x")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("X");
    this.appendValueInput("y")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Y");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("");
  }
};

Blockly.Blocks['char_lcd_backlight'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("LCD Backlight");
    this.appendDummyInput()
        .appendField("On/Off:")
        .appendField(new Blockly.FieldDropdown([["ON", "ON"], ["OFF", "OFF"]]), "on_off");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Turn On/Off the backlight");
  }
};

Blockly.Blocks['char_lcd_display'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("LCD Power");
    this.appendDummyInput()
        .appendField("On/Off:")
        .appendField(new Blockly.FieldDropdown([["ON", "ON"], ["OFF", "OFF"]]), "on_off");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("olive");
    this.setTooltip("Turn ON/Off the display");
  }
};

// ---- OneWire (ds18x20.blockdef.yaml) -----------------------------------------

Blockly.Blocks['onewire_ds18x20_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init OneWire Bus");
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("GPIO");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['onewire_ds18x20_scan'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Scan DS1820 sensors");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['onewire_ds18x20_convert'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Trigger DS1820 reading");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['onewire_ds18x20_read_temp'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("DS1820 Temperature reading");
    this.appendValueInput("rom")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ID");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- Rotatory Encoder (encoder.blockdef.yaml) --------------------------------

Blockly.Blocks['encoder_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init Rotatory Encoder");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/encoder.png", 55, 55, "*"));
    this.appendValueInput("p0")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ch0");
    this.appendValueInput("p1")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ch1");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['encoder_reset'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Reset Encoder");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['encoder_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read Encoder Value");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- GPS (gps.blockdef.yaml) -------------------------------------------------

Blockly.Blocks['gps_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GPS Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/ublox_gps.png", 55, 55, "*"));
    this.appendValueInput("uart")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("UART");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX");
    this.appendValueInput("rx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("RX");
    this.appendValueInput("bps")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Baud Rate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_update'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update GPS Readings");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_coord_format'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Coordinate Format ")
        .appendField(new Blockly.FieldDropdown([["Decimal Degrees (DD)", "dd"], ["Degree Minute Second (DMS)", "dms"]]), "format");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_lat'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Latitude");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_long'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Longitude");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_height'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Altitude");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_speed'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Speed");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_date'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Date");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['gps_get_time'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GPS Timestamp");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- GY33 I2C (gy33_i2c.blockdef.yaml) ---------------------------------------

Blockly.Blocks['gy33_i2c_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GY33 I2C Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/GY-33.jpg", 65, 65, "*"));
    this.appendValueInput("id")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ID");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("freq")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Frequency");
    this.appendValueInput("addr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Initalizes the GY-33 I2C Interface");
  }
};

Blockly.Blocks['gy33_i2c_led_pwr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set LED Power");
    this.appendValueInput("led_pwr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Power");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the brightness of the LED (0 - 10)");
  }
};

Blockly.Blocks['gy33_i2c_cal_white_balance'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Balance Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white balance calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_i2c_cal_white'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_i2c_cal_black'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Black Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a black calibration. The sensor should first be placed on a suitable black surface.");
  }
};

Blockly.Blocks['gy33_i2c_get_all'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get All Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing the Raw Red, Raw Green, Raw Blue, Clear, Lux, Color Temperature, Red, Green, Blue, Color values");
  }
};

Blockly.Blocks['gy33_i2c_get_raw'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Raw Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing only the Raw Red, Raw Green, Raw Blue, Clear values.");
  }
};

Blockly.Blocks['gy33_i2c_get_calibrated'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Calibrated Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing only the calibrated Red, Green, Blue, and Clear values.");
  }
};

// ---- GY33 UART (gy33_uart.blockdef.yaml) -------------------------------------

Blockly.Blocks['gy33_uart_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GY33 UART Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/GY-33.jpg", 65, 65, "*"));
    this.appendValueInput("uart")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("UART");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX");
    this.appendValueInput("rx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("RX");
    this.appendValueInput("bps")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Baud Rate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Initalizes the GY-33 UART");
  }
};

Blockly.Blocks['gy33_uart_led_pwr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set LED Power");
    this.appendValueInput("led_pwr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Power");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the brightness of the LED (0 - 10)");
  }
};

Blockly.Blocks['gy33_uart_integration_time'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Integration Time");
    this.appendDummyInput()
        .appendField("Time (ms)")
        .appendField(new Blockly.FieldDropdown([["700", "700"], ["154", "154"], ["100 (Default)", "100"], ["24", "24"], ["2.4", "2.4"]]), "TIME");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the integration time in milliseconds");
  }
};

Blockly.Blocks['gy33_uart_baud_rate'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Internal UART Baudrate");
    this.appendDummyInput()
        .appendField("Time (ms)")
        .appendField(new Blockly.FieldDropdown([["9600", "9600"], ["115200", "115200"]]), "BAUDRATE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the baudrate");
  }
};

Blockly.Blocks['gy33_uart_i2c_addr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set I2C Address");
    this.appendValueInput("addr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the desired i2c address. Must be between 0 to 127");
  }
};

Blockly.Blocks['gy33_uart_cal_white_balance'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Balance Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white balance calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_uart_cal_white'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_uart_cal_black'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Black Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a black calibration. The sensor should first be placed on a suitable black surface.");
  }
};

Blockly.Blocks['gy33_uart_get_raw'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Raw Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a list containing the raw Red, Green, Blue, Clear values.");
  }
};

Blockly.Blocks['gy33_uart_get_lcc'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get LCC Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a list containing the Lux (brightness), Color Temperature, Color values.");
  }
};

Blockly.Blocks['gy33_uart_get_processed'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Processed Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a list containing the processed Red, Green, Blue values.");
  }
};

// ---- %{BKY_CAT_ULTRASOUND} (hcsr04.blockdef.yaml) ----------------------------

Blockly.Blocks['hcsr_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/hcsr04.png", 55, 55, "*"))
        .appendField(MSG["hcsr_init"]);
    this.appendValueInput("echo")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("echo pin");
    this.appendValueInput("trigger")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("trigger pin");
    this.appendValueInput("timeout")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(new Blockly.FieldLabelSerializable(MSG["hcsr_timeout"]), "DHT_PIN_MSG");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip(MSG["hcsr_init"]);
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['hcsr_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldLabelSerializable(MSG["get_distance"]), "MSG_READ_DHT_TEMP");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip(MSG["measure_distance"]);
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- Oximeter (max30100.blockdef.yaml) ---------------------------------------

Blockly.Blocks['max30100_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init MAX30100 Sensor");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/max30100.png", 55, 55, "*"));
    this.appendValueInput("i2c")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("I2C");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['max30100_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update MAX30100 Reading");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['max30100_red'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get MAX30100 Red Value");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['max30100_ir'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get MAX30100 IR Value");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

// ---- I/O Expander (mcp23017.blockdef.yaml) -----------------------------------

Blockly.Blocks['mcp23017_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init MCP23017");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['mcp23017_setup'] = {
  init: function() {
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("MCP23017 direction setup (IN/OUT)");
    this.appendValueInput("value")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(MSG["to"]);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("MCP23017 directin setup");
    this.setHelpUrl("bipes.net.br");
  }
};

Blockly.Blocks['mcp23017_output'] = {
  init: function() {
    this.appendValueInput("pin")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("MCP23017 set pin");
    this.appendValueInput("value")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField(MSG["to"]);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("MCP23017 Write to GPIO digital pin");
    this.setHelpUrl("bipes.net.br");
  }
};

Blockly.Blocks['mcp23017_input'] = {
  init: function() {
    this.appendValueInput("pin")
        .setCheck("Number")
        .appendField("MCP23017 input pin");
    this.appendValueInput("pullup")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Pull-up");
    this.setOutput(true, null);
    this.setColour(230);
    this.setTooltip("MCP23017 Read digital pin");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- LED Matrix (tm1640.blockdef.yaml) ---------------------------------------

Blockly.Blocks['tm1640_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/matrix.png", 55, 55, "*"))
        .appendField("Start TM1640 LED Matrix");
    this.appendValueInput("clk")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("CLK");
    this.appendValueInput("dio")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("DIO");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Start TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1640_write'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write array to Led Matrix");
    this.appendValueInput("vector")
        .setCheck("String")
        .appendField("LED array value");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Write to TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1640_brig'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Brightness of Led Matrix");
    this.appendValueInput("brig")
        .setCheck("Number")
        .appendField("value (1-7)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Set brightness of TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

Blockly.Blocks['tm1640_num'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Write Number on Led Matrix");
    this.appendValueInput("num")
        .setCheck("Number")
        .appendField("value (0-9)");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("Write number on TM1640 LED Matrix");
    this.setHelpUrl("http://www.bipes.net.br");
  }
};

// ---- UART (uart.blockdef.yaml) -----------------------------------------------

Blockly.Blocks['uart_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init UART Serial Port");
    this.appendValueInput("port")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Port:");
    this.appendValueInput("baud")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Baud rate:");
    this.appendValueInput("tx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("TX Pin:");
    this.appendValueInput("rx")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("RX Pin:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_write'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Send data to UART");
    this.appendValueInput("buf")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Data:");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_read'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read data from UART");
    this.appendValueInput("s")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Bytes to read:");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_read_into'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read from UART into a Buffer");
    this.appendValueInput("b")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Destination Buffer:");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_readline'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read one line from UART");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_read_all'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Read all data from UART");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};

Blockly.Blocks['uart_any'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Check to see if the uart has data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("");
  }
};
