// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written blocks live in
// block_definitions.js; a block belongs in exactly one of the two.

// ---- GY33 I2C (gy33_i2c.blockdef.yaml) --------------------------

Blockly.Blocks['gy33_i2c_init'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Init GY33 I2C Module");
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("media/GY-33.jpg", 65, 65, "*"));
    this.appendValueInput("id")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("ID");
    this.appendValueInput("sda")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SDA");
    this.appendValueInput("scl")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("SCL");
    this.appendValueInput("freq")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Frequency");
    this.appendValueInput("addr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Address");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Initalizes the GY-33 I2C Interface");
  }
};

Blockly.Blocks['gy33_i2c_led_pwr'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set LED Power");
    this.appendValueInput("led_pwr")
        .setCheck("Number")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("Power");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Sets the brightness of the LED (0 - 10)");
  }
};

Blockly.Blocks['gy33_i2c_cal_white_balance'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Balance Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white balance calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_i2c_cal_white'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("White Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a white calibration. The sensor should first be placed on a suitable white surface.");
  }
};

Blockly.Blocks['gy33_i2c_cal_black'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Black Calibrate");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(135);
    this.setTooltip("Performs a black calibration. The sensor should first be placed on a suitable black surface.");
  }
};

Blockly.Blocks['gy33_i2c_get_all'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get All Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing the Raw Red, Raw Green, Raw Blue, Clear, Lux, Color Temperature, Red, Green, Blue, Color values");
  }
};

Blockly.Blocks['gy33_i2c_get_raw'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Raw Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing only the Raw Red, Raw Green, Raw Blue, Clear values.");
  }
};

Blockly.Blocks['gy33_i2c_get_calibrated'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Calibrated Data");
    this.setOutput(true, null);
    this.setColour(135);
    this.setTooltip("Returns a tuple containing only the calibrated Red, Green, Blue, and Clear values.");
  }
};
