// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written generators live in
// generator_stubs.js; a generator belongs in exactly one of the two.

// ---- AHT10/20 Sensor (ahtx0.blockdef.yaml) -----------------------------------

Blockly.Python['aht_init'] = function(block) {
  Blockly.Python.definitions_["import_ahtx0"] = "import ahtx0";
  var AHT_TYPE_ = block.getFieldValue("AHT_TYPE");
  var i2c_ = Blockly.Python.valueToCode(block, "i2c", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({id: i2c_, scl: scl_, sda: sda_});
  var code = "ahtx0=ahtx0." + AHT_TYPE_ + "(" + bus_ + ")";
  return code + "\n";
};

Blockly.Python['aht_read_temp'] = function(block) {
  Blockly.Python.definitions_["import_ahtx0"] = "import ahtx0";
  var code = "ahtx0.temperature";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['aht_read_humidity'] = function(block) {
  Blockly.Python.definitions_["import_ahtx0"] = "import ahtx0";
  var code = "ahtx0.relative_humidity";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- BH1750 Sensor (bh1750.blockdef.yaml) ------------------------------------

Blockly.Python['bh1750_init'] = function(block) {
  Blockly.Python.definitions_["import_bh1750"] = "from bh1750 import BH1750";
  var i2c_ = Blockly.Python.valueToCode(block, "i2c", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({id: i2c_, scl: scl_, sda: sda_});
  var code = "bh1750 = BH1750(35, " + bus_ + ")";
  return code + "\n";
};

Blockly.Python['bh1750_read'] = function(block) {
  Blockly.Python.definitions_["import_bh1750"] = "from bh1750 import BH1750";
  var code = "bh1750.measurement";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- Bluetooth REPL (bluetooth_repl.blockdef.yaml) ---------------------------

Blockly.Python['bluetooth_repl_setup'] = function(block) {
  Blockly.Python.definitions_["import_bluetoot_repl"] = "import ble_uart_repl";
  var name_ = Blockly.Python.valueToCode(block, "name", Blockly.Python.ORDER_ATOMIC);
  var code = "";
  return code + "\n";
};

Blockly.Python['bluetooth_repl_start'] = function(block) {
  Blockly.Python.definitions_["import_bluetoot_repl"] = "import ble_uart_repl";
  var name_ = Blockly.Python.valueToCode(block, "name", Blockly.Python.ORDER_ATOMIC);
  var code = "ble_uart_repl.start(" + name_ + ")";
  return code + "\n";
};

// ---- %{BKY_CAT_PRESS} (bmp.blockdef.yaml) ------------------------------------

Blockly.Python['bmp180_init'] = function(block) {
  Blockly.Python.definitions_["import_bmp180"] = "from bmp180 import BMP180";
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({scl: scl_, sda: sda_, freq: "100000", soft: true});
  var code = "bmp180 = BMP180(" + bus_ + ")\nbmp180.oversample_sett = 2\nbmp180.baseline = 101325\n";
  return code + "\n";
};

Blockly.Python['bmp180_temperature'] = function(block) {
  Blockly.Python.definitions_["import_bmp180"] = "from bmp180 import BMP180";
  var code = "bmp180.temperature";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['bmp180_pressure'] = function(block) {
  Blockly.Python.definitions_["import_bmp180"] = "from bmp180 import BMP180";
  var code = "bmp180.pressure";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['bmp180_altitude'] = function(block) {
  Blockly.Python.definitions_["import_bmp180"] = "from bmp180 import BMP180";
  var code = "bmp180.altitude";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['bmp280_init'] = function(block) {
  Blockly.Python.definitions_["import_bmp280"] = "from bmp280 import *";
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({scl: scl_, sda: sda_, soft: true});
  var code = "bmp280 = BMP280(" + bus_ + ")\nbmp280.use_case(BMP280_CASE_WEATHER)\nbmp280.oversample(BMP280_OS_HIGH)";
  return code + "\n";
};

Blockly.Python['bmp280_measure'] = function(block) {
  Blockly.Python.definitions_["import_bmp280"] = "from bmp280 import *";
  var code = "bmp280.normal_measure()";
  return code + "\n";
};

Blockly.Python['bmp280_sleep'] = function(block) {
  Blockly.Python.definitions_["import_bmp280"] = "from bmp280 import *";
  var code = "bmp280.sleep()";
  return code + "\n";
};

Blockly.Python['bmp280_temperature'] = function(block) {
  Blockly.Python.definitions_["import_bmp280"] = "from bmp280 import *";
  var code = "bmp280.temperature";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['bmp280_pressure'] = function(block) {
  Blockly.Python.definitions_["import_bmp280"] = "from bmp280 import *";
  var code = "bmp280.pressure";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- %{BKY_CAT_AIR} (ccs811.blockdef.yaml) -----------------------------------

Blockly.Python['ccs811_init'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({scl: scl_, sda: sda_, soft: true});
  var code = "sCCS811 = CCS811.CCS811(i2c=" + bus_ + ", addr=90)";
  return code + "\n";
};

Blockly.Python['ccs811_data_ready'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var code = "sCCS811.data_ready()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['ccs811_eCO2'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var code = "sCCS811.eCO2";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['ccs811_tVOC'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var code = "sCCS811.tVOC";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- Character display (char_lcd.blockdef.yaml) ------------------------------

Blockly.Python['char_lcd_init'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var i2c_ = Blockly.Python.valueToCode(block, "i2c", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var rows_ = Blockly.Python.valueToCode(block, "rows", Blockly.Python.ORDER_ATOMIC);
  var columns_ = Blockly.Python.valueToCode(block, "columns", Blockly.Python.ORDER_ATOMIC);
  var LCD_hex_address_ = block.getFieldValue("LCD_hex_address");
  var bus_ = Blockly.Python.i2cBus_({id: i2c_, scl: scl_, sda: sda_, freq: "400000"});
  var code = "I2C_ADDR = " + LCD_hex_address_ + " # NOTE: Be sure to set address\nlcd = I2cLcd(" + bus_ + ", I2C_ADDR, " + rows_ + ", " + columns_ + ")";
  return code + "\n";
};

Blockly.Python['char_lcd_clear'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var code = "lcd.clear()";
  return code + "\n";
};

Blockly.Python['char_lcd_putstr'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var text_ = Blockly.Python.valueToCode(block, "text", Blockly.Python.ORDER_ATOMIC);
  var code = "lcd.putstr(" + text_ + ")";
  return code + "\n";
};

Blockly.Python['char_lcd_moveto'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var x_ = Blockly.Python.valueToCode(block, "x", Blockly.Python.ORDER_ATOMIC);
  var y_ = Blockly.Python.valueToCode(block, "y", Blockly.Python.ORDER_ATOMIC);
  var code = "lcd.move_to(" + x_ + ", " + y_ + ")";
  return code + "\n";
};

Blockly.Python['char_lcd_backlight'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var on_off_ = {"ON": "backlight_on", "OFF": "backlight_off"}[block.getFieldValue("on_off")];
  var code = "lcd." + on_off_ + "()";
  return code + "\n";
};

Blockly.Python['char_lcd_display'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var on_off_ = {"ON": "display_on", "OFF": "display_off"}[block.getFieldValue("on_off")];
  var code = "lcd." + on_off_ + "()";
  return code + "\n";
};

// ---- DC Motor (dc_motor.blockdef.yaml) ---------------------------------------

Blockly.Python['dc_motor_init'] = function(block) {
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  Blockly.Python.definitions_["import_pwm"] = "from machine import PWM";
  var pwm_ = Blockly.Python.valueToCode(block, "pwm", Blockly.Python.ORDER_ATOMIC);
  var dir1_ = Blockly.Python.valueToCode(block, "dir1", Blockly.Python.ORDER_ATOMIC);
  var dir2_ = Blockly.Python.valueToCode(block, "dir2", Blockly.Python.ORDER_ATOMIC);
  var code = "dc_motor_pin_a = Pin(" + dir1_ + ", Pin.OUT)\ndc_motor_pin_b = Pin(" + dir2_ + ", Pin.OUT)\ndc_motor_pwm = PWM(Pin(" + pwm_ + "))";
  return code + "\n";
};

Blockly.Python['dc_motor_power'] = function(block) {
  var power_ = Blockly.Python.valueToCode(block, "power", Blockly.Python.ORDER_ATOMIC);
  var code = "dc_motor_pwm.duty(" + power_ + ")";
  return code + "\n";
};

Blockly.Python['dc_motor_direction'] = function(block) {
  var dir_ = Blockly.Python.valueToCode(block, "dir", Blockly.Python.ORDER_ATOMIC);
  var code = "dc_motor_dir = int(" + dir_ + ")\ndc_motor_pin_a.value(dc_motor_dir & 1)\ndc_motor_pin_b.value((dc_motor_dir >> 1) & 1)";
  return code + "\n";
};

Blockly.Python['dc_motor_stop'] = function(block) {
  var code = "dc_motor_pin_a.value(0)\ndc_motor_pin_b.value(0)";
  return code + "\n";
};

// ---- OneWire (ds18x20.blockdef.yaml) -----------------------------------------

Blockly.Python['onewire_ds18x20_init'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var pin_ = Blockly.Python.valueToCode(block, "pin", Blockly.Python.ORDER_ATOMIC);
  var code = "onewire_pin = Pin(" + pin_ + ")\nds = ds18x20.DS18X20(onewire.OneWire(onewire_pin))";
  return code + "\n";
};

Blockly.Python['onewire_ds18x20_scan'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  var code = "ds.scan()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['onewire_ds18x20_convert'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  var code = "ds.convert_temp()";
  return code + "\n";
};

Blockly.Python['onewire_ds18x20_read_temp'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  var rom_ = Blockly.Python.valueToCode(block, "rom", Blockly.Python.ORDER_ATOMIC);
  var code = "ds.read_temp(" + rom_ + ")";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- Rotatory Encoder (encoder.blockdef.yaml) --------------------------------

Blockly.Python['encoder_init'] = function(block) {
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  Blockly.Python.definitions_["import_encoder_class"] = "\n\n#Encoder class\n#Source: https://github.com/peterhinch/micropython-samples/blob/master/encoders/encoder_portable.py\nclass Encoder(object):\n    def __init__(self, pin_x, pin_y, reverse, scale):\n        self.reverse = reverse\n        self.scale = scale\n        self.forward = True\n        self.pin_x = pin_x\n        self.pin_y = pin_y\n        self._pos = 0\n        self.x_interrupt = pin_x.irq(trigger=Pin.IRQ_RISING | Pin.IRQ_FALLING, handler=self.x_callback)\n        self.y_interrupt = pin_y.irq(trigger=Pin.IRQ_RISING | Pin.IRQ_FALLING, handler=self.y_callback)\n\n    def x_callback(self, line):\n        self.forward = self.pin_x.value() ^ self.pin_y.value() ^ self.reverse\n        self._pos += 1 if self.forward else -1\n\n    def y_callback(self, line):\n        self.forward = self.pin_x.value() ^ self.pin_y.value() ^ self.reverse ^ 1\n        self._pos += 1 if self.forward else -1\n\n    @property\n    def position(self):\n        return self._pos * self.scale\n\n    @position.setter\n    def position(self, value):\n        self._pos = value // self.scale\n\n  ";
  var p0_ = Blockly.Python.valueToCode(block, "p0", Blockly.Python.ORDER_ATOMIC);
  var p1_ = Blockly.Python.valueToCode(block, "p1", Blockly.Python.ORDER_ATOMIC);
  var code = "p00 = Pin(" + p0_ + ", Pin.IN)\np11 = Pin(" + p1_ + ", Pin.IN)\nencoder = Encoder(p00,p11,1,1)";
  return code + "\n";
};

Blockly.Python['encoder_reset'] = function(block) {
  var code = "encoder.position=0";
  return code + "\n";
};

Blockly.Python['encoder_read'] = function(block) {
  var code = "encoder.position";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- GPS (gps.blockdef.yaml) -------------------------------------------------

Blockly.Python['gps_init'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var uart_ = Blockly.Python.valueToCode(block, "uart", Blockly.Python.ORDER_ATOMIC);
  var tx_ = Blockly.Python.valueToCode(block, "tx", Blockly.Python.ORDER_ATOMIC);
  var rx_ = Blockly.Python.valueToCode(block, "rx", Blockly.Python.ORDER_ATOMIC);
  var bps_ = Blockly.Python.valueToCode(block, "bps", Blockly.Python.ORDER_ATOMIC);
  var code = "uartGPS = UART(" + uart_ + ", tx=Pin(" + tx_ + "), rx=Pin(" + rx_ + "))\nuartGPS.init(" + bps_ + ", bits=8, parity=None, stop=1)\ngps = MicropyGPS()";
  return code + "\n";
};

Blockly.Python['gps_update'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "if uartGPS.any():\n\tc=int.from_bytes(uartGPS.read(1), \"big\")\n\tstat = gps.update(chr(c))";
  return code + "\n";
};

Blockly.Python['gps_coord_format'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var format_ = block.getFieldValue("format");
  var code = "gps.coord_format='" + format_ + "'";
  return code + "\n";
};

Blockly.Python['gps_get_lat'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "gps.latitude";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gps_get_long'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "gps.longitude";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gps_get_height'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "gps.altitude";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gps_get_speed'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "gps.speed";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gps_get_date'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "gps.date";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gps_get_time'] = function(block) {
  Blockly.Python.definitions_["import_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_micropyGPS"] = "from mini_micropyGPS import MicropyGPS";
  var code = "gps.timestamp";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- GY33 I2C (gy33_i2c.blockdef.yaml) ---------------------------------------

Blockly.Python['gy33_i2c_init'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var id_ = Blockly.Python.valueToCode(block, "id", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var freq_ = Blockly.Python.valueToCode(block, "freq", Blockly.Python.ORDER_ATOMIC);
  var addr_ = Blockly.Python.valueToCode(block, "addr", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({id: "id=" + id_, scl: scl_, sda: sda_, freq: freq_});
  var code = "gy33_i2c = gy33I2C.GY33_I2C(" + bus_ + ", " + addr_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_i2c_led_pwr'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var led_pwr_ = Blockly.Python.valueToCode(block, "led_pwr", Blockly.Python.ORDER_ATOMIC);
  var code = "gy33_i2c.set_led(" + led_pwr_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_i2c_cal_white_balance'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.calibrate_white_balance()";
  return code + "\n";
};

Blockly.Python['gy33_i2c_cal_white'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.calibrate_white()";
  return code + "\n";
};

Blockly.Python['gy33_i2c_cal_black'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.calibrate_black()";
  return code + "\n";
};

Blockly.Python['gy33_i2c_get_all'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.read_all()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gy33_i2c_get_raw'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.read_raw()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gy33_i2c_get_calibrated'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.read_calibrated()";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- GY33 UART (gy33_uart.blockdef.yaml) -------------------------------------

Blockly.Python['gy33_uart_init'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var uart_ = Blockly.Python.valueToCode(block, "uart", Blockly.Python.ORDER_ATOMIC);
  var tx_ = Blockly.Python.valueToCode(block, "tx", Blockly.Python.ORDER_ATOMIC);
  var rx_ = Blockly.Python.valueToCode(block, "rx", Blockly.Python.ORDER_ATOMIC);
  var bps_ = Blockly.Python.valueToCode(block, "bps", Blockly.Python.ORDER_ATOMIC);
  var code = "uartGY33 = UART(" + uart_ + ", baudrate = " + bps_ + ", tx=Pin(" + tx_ + "), rx=Pin(" + rx_ + "))\ngy33_uart = gy33UART.GY33_UART(uartGY33)\ngy33_uart.set_output(False, False, False)";
  return code + "\n";
};

Blockly.Python['gy33_uart_led_pwr'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var led_pwr_ = Blockly.Python.valueToCode(block, "led_pwr", Blockly.Python.ORDER_ATOMIC);
  var code = "gy33_uart.set_led(" + led_pwr_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_uart_integration_time'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var TIME_ = block.getFieldValue("TIME");
  var code = "gy33_uart.set_integration_time(" + TIME_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_uart_baud_rate'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var BAUDRATE_ = block.getFieldValue("BAUDRATE");
  var code = "gy33_uart.set_baudrate(" + BAUDRATE_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_uart_i2c_addr'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var addr_ = Blockly.Python.valueToCode(block, "addr", Blockly.Python.ORDER_ATOMIC);
  var code = "gy33_uart.set_i2c_addr(" + addr_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_uart_cal_white_balance'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var code = "gy33_uart.calibrate_white_balance()";
  return code + "\n";
};

Blockly.Python['gy33_uart_cal_white'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var code = "gy33_uart.calibrate_white()";
  return code + "\n";
};

Blockly.Python['gy33_uart_cal_black'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var code = "gy33_uart.calibrate_black()";
  return code + "\n";
};

Blockly.Python['gy33_uart_get_raw'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var code = "gy33_uart.get_raw()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gy33_uart_get_lcc'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var code = "gy33_uart.get_lcc()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gy33_uart_get_processed'] = function(block) {
  Blockly.Python.definitions_["import_uart_pin"] = "from machine import UART, Pin";
  Blockly.Python.definitions_["import_gy33_uart"] = "import gy33UART";
  var code = "gy33_uart.get_processed()";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- %{BKY_CAT_ULTRASOUND} (hcsr04.blockdef.yaml) ----------------------------

Blockly.Python['hcsr_init'] = function(block) {
  Blockly.Python.definitions_["import_hcr"] = "from hcsr04 import HCSR04";
  Blockly.Python.definitions_["import_time"] = "import time";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var echo_ = Blockly.Python.valueToCode(block, "echo", Blockly.Python.ORDER_ATOMIC);
  var trigger_ = Blockly.Python.valueToCode(block, "trigger", Blockly.Python.ORDER_ATOMIC);
  var timeout_ = Blockly.Python.valueToCode(block, "timeout", Blockly.Python.ORDER_ATOMIC);
  var code = "ultraSoundSensor = HCSR04(" + "trigger_pin=" + trigger_ + ", echo_pin=" + echo_ + ", echo_timeout_us=" + timeout_ + ")";
  return code + "\n";
};

Blockly.Python['hcsr_read'] = function(block) {
  Blockly.Python.definitions_["import_hcr"] = "from hcsr04 import HCSR04";
  var code = "ultraSoundSensor.distance_mm()";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- Oximeter (max30100.blockdef.yaml) ---------------------------------------

Blockly.Python['max30100_init'] = function(block) {
  Blockly.Python.definitions_["import_MAX30100"] = "import max30100";
  var i2c_ = Blockly.Python.valueToCode(block, "i2c", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({id: i2c_, scl: scl_, sda: sda_});
  var code = "max30100Sensor = max30100.MAX30100(i2c = " + bus_ + ")\nmax30100Sensor.enable_spo2()";
  return code + "\n";
};

Blockly.Python['max30100_read'] = function(block) {
  Blockly.Python.definitions_["import_MAX30100"] = "import max30100";
  var code = "max30100Sensor.read_sensor()";
  return code + "\n";
};

Blockly.Python['max30100_red'] = function(block) {
  Blockly.Python.definitions_["import_MAX30100"] = "import max30100";
  var code = "max30100Sensor.red";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['max30100_ir'] = function(block) {
  Blockly.Python.definitions_["import_MAX30100"] = "import max30100";
  var code = "max30100Sensor.ir";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- I/O Expander (mcp23017.blockdef.yaml) -----------------------------------

Blockly.Python['mcp23017_init'] = function(block) {
  Blockly.Python.definitions_["import_mcp23017"] = "import mcp23017";
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var code = "mcpIO = mcp23017.MCP23017(gpioScl=" + scl_ + ", gpioSda=" + sda_ + ")";
  return code + "\n";
};

Blockly.Python['mcp23017_setup'] = function(block) {
  Blockly.Python.definitions_["import_mcp23017"] = "import mcp23017";
  var pin_ = Blockly.Python.valueToCode(block, "pin", Blockly.Python.ORDER_ATOMIC);
  var value_ = Blockly.Python.valueToCode(block, "value", Blockly.Python.ORDER_ATOMIC);
  var code = "mcpIO.setup(" + pin_ + "," + value_ + ")";
  return code + "\n";
};

Blockly.Python['mcp23017_output'] = function(block) {
  Blockly.Python.definitions_["import_mcp23017"] = "import mcp23017";
  var pin_ = Blockly.Python.valueToCode(block, "pin", Blockly.Python.ORDER_ATOMIC);
  var value_ = Blockly.Python.valueToCode(block, "value", Blockly.Python.ORDER_ATOMIC);
  var code = "mcpIO.output(" + pin_ + "," + value_ + ")";
  return code + "\n";
};

Blockly.Python['mcp23017_input'] = function(block) {
  Blockly.Python.definitions_["import_mcp23017"] = "import mcp23017";
  var pin_ = Blockly.Python.valueToCode(block, "pin", Blockly.Python.ORDER_ATOMIC);
  var pullup_ = Blockly.Python.valueToCode(block, "pullup", Blockly.Python.ORDER_ATOMIC);
  var code = "mcpIO.input(" + pin_ + ")";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- TCP/IP Socket (socket.blockdef.yaml) ------------------------------------

Blockly.Python['net_socket_connect'] = function(block) {
  Blockly.Python.definitions_["import_socket"] = "import socket";
  var host_ = Blockly.Python.valueToCode(block, "host", Blockly.Python.ORDER_ATOMIC);
  var port_ = Blockly.Python.valueToCode(block, "port", Blockly.Python.ORDER_ATOMIC);
  var code = "addr_info = socket.getaddrinfo(" + host_ + "," + port_ + ")\naddr = addr_info[0][-1]\ns = socket.socket()\ns.connect(addr)";
  return code + "\n";
};

Blockly.Python['net_socket_receive'] = function(block) {
  Blockly.Python.definitions_["import_socket"] = "import socket";
  var bytes_ = Blockly.Python.valueToCode(block, "bytes", Blockly.Python.ORDER_ATOMIC);
  var code = "str(s.recv(" + bytes_ + "), 'utf8')";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['net_socket_send'] = function(block) {
  Blockly.Python.definitions_["import_socket"] = "import socket";
  var bytes_ = Blockly.Python.valueToCode(block, "bytes", Blockly.Python.ORDER_ATOMIC);
  var code = "s.send(bytes(" + bytes_ + ", 'utf8'))";
  return code + "\n";
};

Blockly.Python['net_socket_close'] = function(block) {
  Blockly.Python.definitions_["import_socket"] = "import socket";
  var code = "s.close()";
  return code + "\n";
};

// ---- LED Matrix (tm1640.blockdef.yaml) ---------------------------------------

Blockly.Python['tm1640_init'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var clk_ = Blockly.Python.valueToCode(block, "clk", Blockly.Python.ORDER_ATOMIC);
  var dio_ = Blockly.Python.valueToCode(block, "dio", Blockly.Python.ORDER_ATOMIC);
  var code = "tm = tm1640.TM1640(clk=Pin(" + clk_ + "), dio=Pin(" + dio_ + "))";
  return code + "\n";
};

Blockly.Python['tm1640_write'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var vector_ = Blockly.Python.valueToCode(block, "vector", Blockly.Python.ORDER_ATOMIC).replace(/^'|'$/g, "");
  var code = "tm.write([" + vector_ + "])";
  return code + "\n";
};

Blockly.Python['tm1640_brig'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var brig_ = Blockly.Python.valueToCode(block, "brig", Blockly.Python.ORDER_ATOMIC);
  var code = "tm.brightness(" + brig_ + ")";
  return code + "\n";
};

Blockly.Python['tm1640_num'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var num_ = Blockly.Python.valueToCode(block, "num", Blockly.Python.ORDER_ATOMIC);
  var code = "digits = [0x3c66666e76663c00, 0x7e1818181c181800, 0x7e060c3060663c00, 0x3c66603860663c00, 0x30307e3234383000, 0x3c6660603e067e00, 0x3c66663e06663c00, 0x1818183030667e00, 0x3c66663c66663c00, 0x3c66607c66663c00]\ntm.write_int(digits[" + num_ + "])";
  return code + "\n";
};

// ---- UART (uart.blockdef.yaml) -----------------------------------------------

Blockly.Python['uart_init'] = function(block) {
  Blockly.Python.definitions_["import_machine_uart"] = "from machine import UART";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var port_ = Blockly.Python.valueToCode(block, "port", Blockly.Python.ORDER_ATOMIC);
  var baud_ = Blockly.Python.valueToCode(block, "baud", Blockly.Python.ORDER_ATOMIC);
  var tx_ = Blockly.Python.valueToCode(block, "tx", Blockly.Python.ORDER_ATOMIC);
  var rx_ = Blockly.Python.valueToCode(block, "rx", Blockly.Python.ORDER_ATOMIC);
  var code = "uart = UART(" + port_ + ", baudrate=" + baud_ + ", tx=Pin(" + tx_ + "), rx=Pin(" + rx_ + "))";
  return code + "\n";
};

Blockly.Python['uart_write'] = function(block) {
  var buf_ = Blockly.Python.valueToCode(block, "buf", Blockly.Python.ORDER_ATOMIC);
  var code = "uart.write(" + buf_ + ")";
  return code + "\n";
};

Blockly.Python['uart_read'] = function(block) {
  var s_ = Blockly.Python.valueToCode(block, "s", Blockly.Python.ORDER_ATOMIC);
  var code = "uart.read(" + s_ + ").decode()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['uart_read_into'] = function(block) {
  var b_ = Blockly.Python.valueToCode(block, "b", Blockly.Python.ORDER_ATOMIC);
  var code = "uart.readinto(" + b_ + ")";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['uart_readline'] = function(block) {
  var code = "uart.readline().decode()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['uart_read_all'] = function(block) {
  var code = "uart.read().decode()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['uart_any'] = function(block) {
  var code = "uart.any()";
  return [code, Blockly.Python.ORDER_NONE];
};
