// Generated by gen_blocks.py from blockdef/definitions/*.blockdef.yaml -- DO NOT EDIT.
// Run `make blocks` after changing one. Hand-written generators live in
// generator_stubs.js; a generator belongs in exactly one of the two.

// ---- Bluetooth REPL (bluetooth_repl.blockdef.yaml) ---------------------------

Blockly.Python['bluetooth_repl_setup'] = function(block) {
  Blockly.Python.definitions_["import_bluetoot_repl"] = "import ble_uart_repl";
  var name_ = Blockly.Python.valueToCode(block, "name", Blockly.Python.ORDER_ATOMIC);
  var code = "";
  return code + "\n";
};

Blockly.Python['bluetooth_repl_start'] = function(block) {
  Blockly.Python.definitions_["import_bluetoot_repl"] = "import ble_uart_repl";
  var name_ = Blockly.Python.valueToCode(block, "name", Blockly.Python.ORDER_ATOMIC);
  var code = "ble_uart_repl.start(" + name_ + ")";
  return code + "\n";
};

// ---- %{BKY_CAT_AIR} (ccs811.blockdef.yaml) -----------------------------------

Blockly.Python['ccs811_init'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({scl: scl_, sda: sda_, soft: true});
  var code = "sCCS811 = CCS811.CCS811(i2c=" + bus_ + ", addr=90)";
  return code + "\n";
};

Blockly.Python['ccs811_data_ready'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var code = "sCCS811.data_ready()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['ccs811_eCO2'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var code = "sCCS811.eCO2";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['ccs811_tVOC'] = function(block) {
  Blockly.Python.definitions_["import_ccs811"] = "import CCS811";
  var code = "sCCS811.tVOC";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- Character display (char_lcd.blockdef.yaml) ------------------------------

Blockly.Python['char_lcd_init'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var i2c_ = Blockly.Python.valueToCode(block, "i2c", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var rows_ = Blockly.Python.valueToCode(block, "rows", Blockly.Python.ORDER_ATOMIC);
  var columns_ = Blockly.Python.valueToCode(block, "columns", Blockly.Python.ORDER_ATOMIC);
  var LCD_hex_address_ = block.getFieldValue("LCD_hex_address");
  var bus_ = Blockly.Python.i2cBus_({id: i2c_, scl: scl_, sda: sda_, freq: "400000"});
  var code = "I2C_ADDR = " + LCD_hex_address_ + " # NOTE: Be sure to set address\nlcd = I2cLcd(" + bus_ + ", I2C_ADDR, " + rows_ + ", " + columns_ + ")";
  return code + "\n";
};

Blockly.Python['char_lcd_clear'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var code = "lcd.clear()";
  return code + "\n";
};

Blockly.Python['char_lcd_putstr'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var text_ = Blockly.Python.valueToCode(block, "text", Blockly.Python.ORDER_ATOMIC);
  var code = "lcd.putstr(" + text_ + ")";
  return code + "\n";
};

Blockly.Python['char_lcd_moveto'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var x_ = Blockly.Python.valueToCode(block, "x", Blockly.Python.ORDER_ATOMIC);
  var y_ = Blockly.Python.valueToCode(block, "y", Blockly.Python.ORDER_ATOMIC);
  var code = "lcd.move_to(" + x_ + ", " + y_ + ")";
  return code + "\n";
};

Blockly.Python['char_lcd_backlight'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var on_off_ = {"ON": "backlight_on", "OFF": "backlight_off"}[block.getFieldValue("on_off")];
  var code = "lcd." + on_off_ + "()";
  return code + "\n";
};

Blockly.Python['char_lcd_display'] = function(block) {
  Blockly.Python.definitions_["import_lcd_api"] = "from lcd_api import LcdApi";
  Blockly.Python.definitions_["import_pico_i2c_lcd"] = "from pico_i2c_lcd import I2cLcd";
  var on_off_ = {"ON": "display_on", "OFF": "display_off"}[block.getFieldValue("on_off")];
  var code = "lcd." + on_off_ + "()";
  return code + "\n";
};

// ---- OneWire (ds18x20.blockdef.yaml) -----------------------------------------

Blockly.Python['onewire_ds18x20_init'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var pin_ = Blockly.Python.valueToCode(block, "pin", Blockly.Python.ORDER_ATOMIC);
  var code = "onewire_pin = Pin(" + pin_ + ")\nds = ds18x20.DS18X20(onewire.OneWire(onewire_pin))";
  return code + "\n";
};

Blockly.Python['onewire_ds18x20_scan'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  var code = "ds.scan()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['onewire_ds18x20_convert'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  var code = "ds.convert_temp()";
  return code + "\n";
};

Blockly.Python['onewire_ds18x20_read_temp'] = function(block) {
  Blockly.Python.definitions_["import_onewire"] = "import onewire,ds18x20";
  var rom_ = Blockly.Python.valueToCode(block, "rom", Blockly.Python.ORDER_ATOMIC);
  var code = "ds.read_temp(" + rom_ + ")";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- GY33 I2C (gy33_i2c.blockdef.yaml) ---------------------------------------

Blockly.Python['gy33_i2c_init'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var id_ = Blockly.Python.valueToCode(block, "id", Blockly.Python.ORDER_ATOMIC);
  var sda_ = Blockly.Python.valueToCode(block, "sda", Blockly.Python.ORDER_ATOMIC);
  var scl_ = Blockly.Python.valueToCode(block, "scl", Blockly.Python.ORDER_ATOMIC);
  var freq_ = Blockly.Python.valueToCode(block, "freq", Blockly.Python.ORDER_ATOMIC);
  var addr_ = Blockly.Python.valueToCode(block, "addr", Blockly.Python.ORDER_ATOMIC);
  var bus_ = Blockly.Python.i2cBus_({id: "id=" + id_, scl: scl_, sda: sda_, freq: freq_});
  var code = "gy33_i2c = gy33I2C.GY33_I2C(" + bus_ + ", " + addr_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_i2c_led_pwr'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var led_pwr_ = Blockly.Python.valueToCode(block, "led_pwr", Blockly.Python.ORDER_ATOMIC);
  var code = "gy33_i2c.set_led(" + led_pwr_ + ")";
  return code + "\n";
};

Blockly.Python['gy33_i2c_cal_white_balance'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.calibrate_white_balance()";
  return code + "\n";
};

Blockly.Python['gy33_i2c_cal_white'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.calibrate_white()";
  return code + "\n";
};

Blockly.Python['gy33_i2c_cal_black'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.calibrate_black()";
  return code + "\n";
};

Blockly.Python['gy33_i2c_get_all'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.read_all()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gy33_i2c_get_raw'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.read_raw()";
  return [code, Blockly.Python.ORDER_NONE];
};

Blockly.Python['gy33_i2c_get_calibrated'] = function(block) {
  Blockly.Python.definitions_["import_gy33I2C"] = "import gy33I2C";
  var code = "gy33_i2c.read_calibrated()";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- %{BKY_CAT_ULTRASOUND} (hcsr04.blockdef.yaml) ----------------------------

Blockly.Python['hcsr_init'] = function(block) {
  Blockly.Python.definitions_["import_hcr"] = "from hcsr04 import HCSR04";
  Blockly.Python.definitions_["import_time"] = "import time";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var echo_ = Blockly.Python.valueToCode(block, "echo", Blockly.Python.ORDER_ATOMIC);
  var trigger_ = Blockly.Python.valueToCode(block, "trigger", Blockly.Python.ORDER_ATOMIC);
  var timeout_ = Blockly.Python.valueToCode(block, "timeout", Blockly.Python.ORDER_ATOMIC);
  var code = "ultraSoundSensor = HCSR04(" + "trigger_pin=" + trigger_ + ", echo_pin=" + echo_ + ", echo_timeout_us=" + timeout_ + ")";
  return code + "\n";
};

Blockly.Python['hcsr_read'] = function(block) {
  Blockly.Python.definitions_["import_hcr"] = "from hcsr04 import HCSR04";
  var code = "ultraSoundSensor.distance_mm()";
  return [code, Blockly.Python.ORDER_NONE];
};

// ---- LED Matrix (tm1640.blockdef.yaml) ---------------------------------------

Blockly.Python['tm1640_init'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var clk_ = Blockly.Python.valueToCode(block, "clk", Blockly.Python.ORDER_ATOMIC);
  var dio_ = Blockly.Python.valueToCode(block, "dio", Blockly.Python.ORDER_ATOMIC);
  var code = "tm = tm1640.TM1640(clk=Pin(" + clk_ + "), dio=Pin(" + dio_ + "))";
  return code + "\n";
};

Blockly.Python['tm1640_write'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var vector_ = Blockly.Python.valueToCode(block, "vector", Blockly.Python.ORDER_ATOMIC).replace(/^'|'$/g, "");
  var code = "tm.write([" + vector_ + "])";
  return code + "\n";
};

Blockly.Python['tm1640_brig'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var brig_ = Blockly.Python.valueToCode(block, "brig", Blockly.Python.ORDER_ATOMIC);
  var code = "tm.brightness(" + brig_ + ")";
  return code + "\n";
};

Blockly.Python['tm1640_num'] = function(block) {
  Blockly.Python.definitions_["import_tm1640"] = "import tm1640";
  Blockly.Python.definitions_["import_pin"] = "from machine import Pin";
  var num_ = Blockly.Python.valueToCode(block, "num", Blockly.Python.ORDER_ATOMIC);
  var code = "digits = [0x3c66666e76663c00, 0x7e1818181c181800, 0x7e060c3060663c00, 0x3c66603860663c00, 0x30307e3234383000, 0x3c6660603e067e00, 0x3c66663e06663c00, 0x1818183030667e00, 0x3c66663c66663c00, 0x3c66607c66663c00]\ntm.write_int(digits[" + num_ + "])";
  return code + "\n";
};
